### ISSUE TITLE
Unable to capture a collection of user-defined resources

### ISSUE THREAD

**Issue by eladb** [winglang/wing#1510]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

```js
bring cloud;

resource Foo {
  q: cloud.Queue;

  init() {
    this.q = new cloud.Queue();
  }

  inflight foo() {
    this.q.push("hello");
  }
}

let foos = [new Foo() as "f1"];
new cloud.Function(inflight () => {
  foos.at(0).foo();
}) as "test";
```

### I expected this:

To work

### Instead, this happened:

```
wing test wingr.w
fail | wingr.w | root/test
Error: Missing environment variable: QUEUE_HANDLE_7ca738ac
    at evalmachine.<anonymous>:69:15
    at exports.handler (evalmachine.<anonymous>:72:6)
    at evalmachine.<anonymous>:76:9
    at Script.runInContext (node:vm:141:12)
    at Object.runInContext (node:vm:297:6)
    at Object.activity (/Users/eladb/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-sim/function.inflight.js:86:27)
    at Object.withTrace (/Users/eladb/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/testing/simulator.js:107:50)
    at Function.invoke (/Users/eladb/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-sim/function.inflight.js:83:29)
    at Simulator.runTest (/Users/eladb/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/testing/simulator.js:295:22)
    at async Simulator.runAllTests (/Users/eladb/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/testing/simulator.js:270:26)
```

### Component:

Compiler

### Wing Version:

0.5.28

**Comment by staycoolcall911** [comment]
@Chriscbr - is this issue related to #1531?

**Comment by Chriscbr** [comment]
I'm not sure

**Comment by staycoolcall911** [comment]
Just tried it and it works - closing
