### ISSUE TITLE
Unable to capture `node.addr`

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2145]
### I tried this

```js
bring cloud;

let bucket = new cloud.Bucket();

new cloud.Function(inflight () => {
  bucket.put("addr.txt", bucket.node.addr);
}) as "test";
````

### I expected this:

To print the construct node address.

### Instead, this happened

```
✔ Compiling to sim...
fail ┌ hello.wsim » root/env0/test
     │ TypeError: Cannot read properties of undefined (reading 'addr')
     │     at Handler.handle (/Users/eladb/playground/foo/target/test/hello.wsim/.wing/test_c8c85f80.js:11:44)
     │     at exports.handler (/Users/eladb/playground/foo/target/test/hello.wsim/.wing/test_c8c85f80.js:23:5)
     │     at VM2 Wrapper.apply (/Users/eladb/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/node_modules/vm2/lib/bridge.js:485:11)
     │     at Object.activity (/Users/eladb/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-sim/function.inflight.js:91:30)
     │     at Object.withTrace (/Users/eladb/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/testing/simulator.js:69:50)
     │     at Function.invoke (/Users/eladb/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-sim/function.inflight.js:49:29)
     │     at TestRunnerClient.runTest (/Users/eladb/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-sim/test-runner.inflight.js:31:28)
     │     at testSimulator (/Users/eladb/.volta/tools/image/packages/winglang/lib/node_modules/winglang/dist/commands/test.js:135:39)
     │     at async testOne (/Users/eladb/.volta/tools/image/packages/winglang/lib/node_modules/winglang/dist/commands/test.js:54:13)
     └     at async test (/Users/eladb/.volta/tools/image/packages/winglang/lib/node_modules/winglang/dist/commands/test.js:43:9)
```

### Is there a workaround?

```js
bring cloud;

let bucket = new cloud.Bucket();
let addr = bucket.node.addr;
new cloud.Function(inflight () => {
  bucket.put("addr.txt", addr);
}) as "test";
```

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by eladb** [comment]
Since `Node` is not a resource (or a construct for that matter), I am comfortable for this not work at this point, but we need a reasonable error.

If this is referenced from an inflight *method*, the error is good:

```js
15 |         log(this.b.node.addr);
   |             ^^^^^^^^^^^ Cannot capture field 'node' with non-capturable type 'Node'
```

And since we are planning to convert all inflight closures to resources, I think we can close this specific issue as a duplicate.

**Comment by eladb** [comment]
Dup https://github.com/winglang/wing/issues/1448
