### ISSUE TITLE
Compiler crashes on function type in struct

### ISSUE THREAD

**Issue by flyingImer** [winglang/wing#2161]
### I tried this

```
bring cloud;

struct SomeStruct {
    fn1: inflight (str): void;
}

resource SomeResource {
    init(props: SomeStruct) {}
}
```

### I expected this:

Compiler complains about the unsupported type in struct

### Instead, this happened

Compiler crashed:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ()', libs/wingc/src/parser.rs:780:39
stack backtrace:
RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::h911ba172265603df (wasm://wasm/009828ee:wasm-function[219]:0xc841c)
    at core::panicking::panic_fmt::h6958314cbbe045b2 (wasm://wasm/009828ee:wasm-function[1429]:0x171001)
    at core::result::unwrap_failed::h5a65fd54aeec1613 (wasm://wasm/009828ee:wasm-function[1076]:0x164730)
    at wingc::parser::Parser::build_type_annotation::h5424d89d1fd4e284 (wasm://wasm/009828ee:wasm-function[37]:0x53322)
    at <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::h26adee073cf03de6 (wasm://wasm/009828ee:wasm-function[631]:0x13d46a)
    at <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h4c1ec0ed949f92b1 (wasm://wasm/009828ee:wasm-function[438]:0x116f18)
    at wingc::parser::Parser::wingit::h74229a5a02aa61a0 (wasm://wasm/009828ee:wasm-function[134]:0xa746b)
    at wingc_compile.command_export (wasm://wasm/009828ee:wasm-function[1570]:0x176f63)
    at Object.invoke (/Users/yijiwang/.volta/tools/image/packages/winglang/lib/node_modules/winglang/dist/wingc.js:101:37)
    at compile (/Users/yijiwang/.volta/tools/image/packages/winglang/lib/node_modules/winglang/dist/commands/compile.js:130:38)
```

However, the compiler is fine with (not complaining tho):
```
bring cloud;

struct SomeStruct {
    fn1: inflight (str); // <- removed explicit void return type
}

resource SomeResource {
    init(props: SomeStruct) {}
}
```
or
```
bring cloud;

struct SomeStruct {
    fn1: inflight (str): num; // <- changed to a different explicit num return type
}

resource SomeResource {
    init(props: SomeStruct) {}
}
```

The discrepancy is confusing. However, @Chriscbr [mentioned](https://winglang.slack.com/archives/C048QCN2XLJ/p1681926907472489?thread_ts=1681926549.158929&cid=C048QCN2XLJ) that `struct` is not supposed to take function type anyway, the bug fix would be complier complaining about the unsupported types in `struct`

### Component

Compiler

### Wing Version

0.13.7

### Node.js Version

v18.14.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by eladb** [comment]
The issue here is that we don't yet support `void` as a return type, so the correct syntax for this at the moment is:

```js
struct SomeStruct {
    fn1: inflight (str);
}
```

Yes, I know it's weird. We will fix it: https://github.com/winglang/wing/issues/2234

Closing as dup
