### ISSUE TITLE
Queue.addConsumer code does not work on tf-aws (depends on code)

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#2400]
### I tried this:
** when running other piece of code including the add_consumer it did work, I think this is an edge case
run this code by `wing test -t tf-aws`:
```
bring cloud;

let q = new cloud.Queue();
let c = new cloud.Counter();

class JSHelper {
  init(){}
  extern "../external/sleep.js" inflight sleep(milli: num);
}

q.addConsumer(inflight () => {
  c.inc();
});

let js = new JSHelper();
new cloud.Function(inflight () => {
  q.push("hello");
  q.push("world");
  // TODO: replace this sleep with std.sleep: https://github.com/winglang/wing/issues/1535
  js.sleep(1000);
  let count = c.peek();
  assert(count == 2);
}) as "test";
```

### This happened:

<img width="918" alt="Pasted Graphic 4" src="https://user-images.githubusercontent.com/39455181/234845627-8e984d39-1980-4dea-92fc-58626b8a28ee.png">

### I expected this:

to work with no errors :) 

### Component

SDK

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by marciocadev** [comment]
@tsuf239 The problem is you sleep only 1 second, change the `js.sleep(1000);` to `js.sleep(10000);`

It will pass

## sleep 1 second
```bash
✔ Compiling to tf-aws...
✔ terraform init
✔ terraform apply
✔ Setting up test runner...
✔ Running tests...
fail ┌ invoke.tfaws » root/Default/env0/test
     │ Error: Invoke failed with message: "Unhandled". Full error: "{"errorType":"Error","errorMessage":"assertion failed: '(count === 2)'","trace":["Error: assertion failed: '(count === 2)'","    at /var/task/index.js:54128:21","    at Handler.handle (/var/task/index.js:54129:13)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async exports.handler (/var/task/index.js:54112:10)"]}"
     │     at FunctionClient.invoke (/usr/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/shared-aws/function.inflight.js:21:19)
     │     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     │     at async TestRunnerClient.runTest (/usr/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-tf-aws/test-runner.inflight.js:27:13)
     │     at async /usr/lib/node_modules/winglang/dist/commands/test.js:159:26
     │     at async withSpinner (/usr/lib/node_modules/winglang/dist/util.js:30:24)
     │     at async testTfAws (/usr/lib/node_modules/winglang/dist/commands/test.js:156:21)
     │     at async testOne (/usr/lib/node_modules/winglang/dist/commands/test.js:57:13)
     └     at async test (/usr/lib/node_modules/winglang/dist/commands/test.js:43:9)
One or more tests failed. Cleaning up resources...
✔ terraform destroy
```

##  sleep 10 seconds
```bash
✔ Compiling to tf-aws...
✔ terraform init
✔ terraform apply
✔ Setting up test runner...
✔ Running tests...
pass ─ invoke.tfaws » root/Default/env0/test
✔ terraform destroy
```

**Comment by ekeren** [comment]
I am not sure it is a bug, it might be a timing issue caused by cold start 



The test should use some busywait solution , see this answer as an example https://github.com/winglang/wing/discussions/1762#discussioncomment-5528091
