### ISSUE TITLE
Inner class as handler doesn't work

### ISSUE THREAD

**Issue by yoav-steinberg** [winglang/wing#2472]
### I tried this:

```wing
bring cloud;

class MyResource {
  localTopic: cloud.Topic;
  localCounter: cloud.Counter;
  init() {
    this.localTopic = new cloud.Topic();
    this.localCounter = new cloud.Counter();
    let $parentThis = this;

    // Inner class implementing the handler interface
    class R impl cloud.ITopicOnMessageHandler {
      inflight handle() {
        log("handle");
        $parentThis.localCounter.inc();
      }
    }

    // This doesn't work:
    this.localTopic.onMessage(new R());

    // This works:
    // this.localTopic.onMessage(inflight () => {
    //   log("handle");
    //   $parentThis.localCounter.inc();
    // });
  }

  inflight myPut() {
    this.localTopic.publish("hello");
    assert(this.localCounter.peek() > 0); // TODO: this fails, why?
  }
}

let res = new MyResource();

new cloud.Function(inflight () => {
  res.myPut();
}) as "test";
```

### This happened:

```
apps/wing/bin/wing test temp/tst.w
✔ Compiling to sim...
fail ┌ tst.wsim » root/env0/test
     │ Error: assertion failed: '((await this.localCounter.peek()) > 0)'
     │     at /home/yoav/winglang/temp/target/test/tst.wsim/.wing/clients/MyResource.inflight.js:10:39
     │     at MyResource.myPut (/home/yoav/winglang/temp/target/test/tst.wsim/.wing/clients/MyResource.inflight.js:10:112)
     │     at async Handler.handle (/home/yoav/winglang/temp/target/test/tst.wsim/.wing/test_c8c85f80.js:11:4)
     └     at async exports.handler (/home/yoav/winglang/temp/target/test/tst.wsim/.wing/test_c8c85f80.js:2:10)
```

### I expected this:

```
apps/wing/bin/wing test temp/tst.w
✔ Compiling to sim...
pass ┌ tst.wsim » root/env0/test
     └ handle
```

### Is there a workaround?

When using an inflight closure instead of the inner handler class it works

### Component

Compiler

### Anything else?

Not sure if this is an issue with using preflight class as a handler or the fact it's an inflight class or something else?

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by eladb** [comment]
@Chriscbr any idea why this is happening? Supposedly this should be the same thing, no?

**Comment by staycoolcall911** [comment]
This works. Closing
