### ISSUE TITLE
Extension Language Server crashes

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#2486]
### I tried this:

Browsing through the projects in the [research](https://github.com/winglang/research/) repo. Seemed to generally work, but got a crash notice after switching through a few files.

### This happened:

Got a crash notice 

<details>
```
thread '<unnamed>' panicked at 'assertion failed: (*env).is_none()', libs/wingc/src/ast.rs:607:9
stack backtrace:
wasm://wasm/00995fba:1


RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::h911ba172265603df (wasm://wasm/00995fba:wasm-function[231]:0xcfcd5)
    at core::panicking::panic_fmt::h6958314cbbe045b2 (wasm://wasm/00995fba:wasm-function[1443]:0x177eb3)
    at core::panicking::panic::ha6e963274fcf290b (wasm://wasm/00995fba:wasm-function[1353]:0x174a87)
    at wingc::type_check::TypeChecker::type_check_exp_helper::hc85ab2a4907d58f7 (wasm://wasm/00995fba:wasm-function[20]:0x177ef)
    at wingc::type_check::TypeChecker::type_check_exp_helper::hc85ab2a4907d58f7 (wasm://wasm/00995fba:wasm-function[20]:0x153e7)
    at wingc::type_check::TypeChecker::type_check_exp_helper::hc85ab2a4907d58f7 (wasm://wasm/00995fba:wasm-function[20]:0x15a5c)
    at wingc::type_check::TypeChecker::type_check_scope::h78016c045164aa11 (wasm://wasm/00995fba:wasm-function[433]:0x113b1c)
    at wingc::type_check::hfcd5224edaaf4841 (wasm://wasm/00995fba:wasm-function[108]:0x9ac8b)
    at wingc::lsp::sync::partial_compile::hd79977e7589b4129 (wasm://wasm/00995fba:wasm-function[153]:0xb59fd)
    at wingc_on_did_open_text_document.command_export (wasm://wasm/00995fba:wasm-function[1590]:0x1814eb)
    at Object.invoke (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/dist/wingc.js:145:37)
    at /Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/dist/commands/lsp.js:54:22
    at handleNotification (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/node_modules/vscode-jsonrpc/lib/common/connection.js:640:25)
    at handleMessage (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/node_modules/vscode-jsonrpc/lib/common/connection.js:342:13)
    at processMessageQueue (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)
    at Immediate.<anonymous> (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)
    at process.processImmediate (node:internal/timers:471:21)

Node.js v18.13.0
[Info  - 11:16:03] Connection to server got closed. Server will restart.
thread '<unnamed>' panicked at 'assertion failed: (*env).is_none()', libs/wingc/src/ast.rs:607:9
stack backtrace:
wasm://wasm/00995fba:1


RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::h911ba172265603df (wasm://wasm/00995fba:wasm-function[231]:0xcfcd5)
    at core::panicking::panic_fmt::h6958314cbbe045b2 (wasm://wasm/00995fba:wasm-function[1443]:0x177eb3)
    at core::panicking::panic::ha6e963274fcf290b (wasm://wasm/00995fba:wasm-function[1353]:0x174a87)
    at wingc::type_check::TypeChecker::type_check_exp_helper::hc85ab2a4907d58f7 (wasm://wasm/00995fba:wasm-function[20]:0x177ef)
    at wingc::type_check::TypeChecker::type_check_exp_helper::hc85ab2a4907d58f7 (wasm://wasm/00995fba:wasm-function[20]:0x153e7)
    at wingc::type_check::TypeChecker::type_check_exp_helper::hc85ab2a4907d58f7 (wasm://wasm/00995fba:wasm-function[20]:0x15a5c)
    at wingc::type_check::TypeChecker::type_check_scope::h78016c045164aa11 (wasm://wasm/00995fba:wasm-function[433]:0x113b1c)
    at wingc::type_check::hfcd5224edaaf4841 (wasm://wasm/00995fba:wasm-function[108]:0x9ac8b)
    at wingc::lsp::sync::partial_compile::hd79977e7589b4129 (wasm://wasm/00995fba:wasm-function[153]:0xb59fd)
    at wingc_on_did_open_text_document.command_export (wasm://wasm/00995fba:wasm-function[1590]:0x1814eb)
    at Object.invoke (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/dist/wingc.js:145:37)
    at /Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/dist/commands/lsp.js:54:22
    at handleNotification (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/node_modules/vscode-jsonrpc/lib/common/connection.js:640:25)
    at handleMessage (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/node_modules/vscode-jsonrpc/lib/common/connection.js:342:13)
    at processMessageQueue (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)
    at Immediate.<anonymous> (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)
    at process.processImmediate (node:internal/timers:471:21)

Node.js v18.13.0
[Info  - 11:16:03] Connection to server got closed. Server will restart.
thread '<unnamed>' panicked at 'assertion failed: (*env).is_none()', libs/wingc/src/ast.rs:607:9
stack backtrace:
wasm://wasm/00995fba:1


RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::h911ba172265603df (wasm://wasm/00995fba:wasm-function[231]:0xcfcd5)
    at core::panicking::panic_fmt::h6958314cbbe045b2 (wasm://wasm/00995fba:wasm-function[1443]:0x177eb3)
    at core::panicking::panic::ha6e963274fcf290b (wasm://wasm/00995fba:wasm-function[1353]:0x174a87)
    at wingc::type_check::TypeChecker::type_check_exp_helper::hc85ab2a4907d58f7 (wasm://wasm/00995fba:wasm-function[20]:0x177ef)
    at wingc::type_check::TypeChecker::type_check_exp_helper::hc85ab2a4907d58f7 (wasm://wasm/00995fba:wasm-function[20]:0x153e7)
    at wingc::type_check::TypeChecker::type_check_exp_helper::hc85ab2a4907d58f7 (wasm://wasm/00995fba:wasm-function[20]:0x15a5c)
    at wingc::type_check::TypeChecker::type_check_scope::h78016c045164aa11 (wasm://wasm/00995fba:wasm-function[433]:0x113b1c)
    at wingc::type_check::hfcd5224edaaf4841 (wasm://wasm/00995fba:wasm-function[108]:0x9ac8b)
    at wingc::lsp::sync::partial_compile::hd79977e7589b4129 (wasm://wasm/00995fba:wasm-function[153]:0xb59fd)
    at wingc_on_did_open_text_document.command_export (wasm://wasm/00995fba:wasm-function[1590]:0x1814eb)
    at Object.invoke (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/dist/wingc.js:145:37)
    at /Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/dist/commands/lsp.js:54:22
    at handleNotification (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/node_modules/vscode-jsonrpc/lib/common/connection.js:640:25)
    at handleMessage (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/node_modules/vscode-jsonrpc/lib/common/connection.js:342:13)
    at processMessageQueue (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)
    at Immediate.<anonymous> (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)
    at process.processImmediate (node:internal/timers:471:21)

Node.js v18.13.0
[Info  - 11:16:04] Connection to server got closed. Server will restart.
thread '<unnamed>' panicked at 'assertion failed: (*env).is_none()', libs/wingc/src/ast.rs:607:9
stack backtrace:
wasm://wasm/00995fba:1


RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::h911ba172265603df (wasm://wasm/00995fba:wasm-function[231]:0xcfcd5)
    at core::panicking::panic_fmt::h6958314cbbe045b2 (wasm://wasm/00995fba:wasm-function[1443]:0x177eb3)
    at core::panicking::panic::ha6e963274fcf290b (wasm://wasm/00995fba:wasm-function[1353]:0x174a87)
    at wingc::type_check::TypeChecker::type_check_exp_helper::hc85ab2a4907d58f7 (wasm://wasm/00995fba:wasm-function[20]:0x177ef)
    at wingc::type_check::TypeChecker::type_check_exp_helper::hc85ab2a4907d58f7 (wasm://wasm/00995fba:wasm-function[20]:0x153e7)
    at wingc::type_check::TypeChecker::type_check_exp_helper::hc85ab2a4907d58f7 (wasm://wasm/00995fba:wasm-function[20]:0x15a5c)
    at wingc::type_check::TypeChecker::type_check_scope::h78016c045164aa11 (wasm://wasm/00995fba:wasm-function[433]:0x113b1c)
    at wingc::type_check::hfcd5224edaaf4841 (wasm://wasm/00995fba:wasm-function[108]:0x9ac8b)
    at wingc::lsp::sync::partial_compile::hd79977e7589b4129 (wasm://wasm/00995fba:wasm-function[153]:0xb59fd)
    at wingc_on_did_open_text_document.command_export (wasm://wasm/00995fba:wasm-function[1590]:0x1814eb)
    at Object.invoke (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/dist/wingc.js:145:37)
    at /Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/dist/commands/lsp.js:54:22
    at handleNotification (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/node_modules/vscode-jsonrpc/lib/common/connection.js:640:25)
    at handleMessage (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/node_modules/vscode-jsonrpc/lib/common/connection.js:342:13)
    at processMessageQueue (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)
    at Immediate.<anonymous> (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)
    at process.processImmediate (node:internal/timers:471:21)

Node.js v18.13.0
[Info  - 11:16:05] Connection to server got closed. Server will restart.
thread '<unnamed>' panicked at 'assertion failed: (*env).is_none()', libs/wingc/src/ast.rs:607:9
stack backtrace:
wasm://wasm/00995fba:1


RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::h911ba172265603df (wasm://wasm/00995fba:wasm-function[231]:0xcfcd5)
    at core::panicking::panic_fmt::h6958314cbbe045b2 (wasm://wasm/00995fba:wasm-function[1443]:0x177eb3)
    at core::panicking::panic::ha6e963274fcf290b (wasm://wasm/00995fba:wasm-function[1353]:0x174a87)
    at wingc::type_check::TypeChecker::type_check_exp_helper::hc85ab2a4907d58f7 (wasm://wasm/00995fba:wasm-function[20]:0x177ef)
    at wingc::type_check::TypeChecker::type_check_exp_helper::hc85ab2a4907d58f7 (wasm://wasm/00995fba:wasm-function[20]:0x153e7)
    at wingc::type_check::TypeChecker::type_check_exp_helper::hc85ab2a4907d58f7 (wasm://wasm/00995fba:wasm-function[20]:0x15a5c)
    at wingc::type_check::TypeChecker::type_check_scope::h78016c045164aa11 (wasm://wasm/00995fba:wasm-function[433]:0x113b1c)
    at wingc::type_check::hfcd5224edaaf4841 (wasm://wasm/00995fba:wasm-function[108]:0x9ac8b)
    at wingc::lsp::sync::partial_compile::hd79977e7589b4129 (wasm://wasm/00995fba:wasm-function[153]:0xb59fd)
    at wingc_on_did_open_text_document.command_export (wasm://wasm/00995fba:wasm-function[1590]:0x1814eb)
    at Object.invoke (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/dist/wingc.js:145:37)
    at /Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/dist/commands/lsp.js:54:22
    at handleNotification (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/node_modules/vscode-jsonrpc/lib/common/connection.js:640:25)
    at handleMessage (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/node_modules/vscode-jsonrpc/lib/common/connection.js:342:13)
    at processMessageQueue (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)
    at Immediate.<anonymous> (/Users/sebastian/.nvm/versions/node/v18.13.0/lib/node_modules/winglang/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)
    at process.processImmediate (node:internal/timers:471:21)

Node.js v18.13.0
[Error - 11:16:05] The Wing Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```
</details>

### I expected this:

No crash notice - yes, I saw the extension readme which states that it can crash :)

### Is there a workaround?

probably just restarting

### Component

IDE Extension

### Wing Version

0.17.0

### Node.js Version

v18.13.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Thank you for reporting @skorfmann - do you happen to remember what code you were running that produced this crash?

**Comment by skorfmann** [comment]
> Thank you for reporting @skorfmann - do you happen to remember what code you were running that produced this crash?

Good point - yes, seems to be this [one](https://github.com/winglang/research/blob/b8a710219643a358cbbc55e8c9ac3a1afc756de3/dogfooding/where-to-eat/food.w)

**Comment by staycoolcall911** [comment]
This is another case where our compiler panics when it shouldn't.
Here's a simplified version of the code that causes the crash:
```ts
bring cloud;

class A {

}

resource B {
    init(a: A) {
        this.callFunc(inflight () => {
            
        });
    }
}
```
Looks like either changing `resource` to `class` or removing the inflight closure prevents this panic.

**Comment by staycoolcall911** [comment]
Closing - outdated
