### ISSUE TITLE
Compiler panics when adding interface keyword 

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#2603]
### I tried this:

```ts (wing)
bring cloud;
bring redis;

let api = new cloud.Api();

interface // this line cause panic



class FibCalculator { 
  mem: redis.Redis;
  init() {
    this.mem = new redis.Redis();  
  }
  inflight calc(n: num):num {
    let storedResult = this.mem.get("${n}");
    if storedResult? {
      return num.fromStr(storedResult ?? "-1");
    }
    if n == 0 {
      return 0;
    }
    if n == 1 {
      return 1;
    }
    let res = this.calc(n-2) + this.calc(n-1);
    this.mem.set("${n}", "${res}");
    return res;
  }
}

let fib = new FibCalculator();
api.get("/fib/{n}", inflight (req: cloud.ApiRequest): cloud.ApiResponse => {
  let n = num.fromStr(req.vars.get("n"));
  return cloud.ApiResponse { status: 200, body: fib.calc(n) };
});

test "fib" {
  assert(fib.calc(0) == 0);
  assert(fib.calc(1) == 1);
  assert(fib.calc(2) == 1);
  assert(fib.calc(3) == 2);
  assert(fib.calc(4) == 3);
}
```

### This happened:

compiler paniced

```
wing compile -t sim app.w 
thread '<unnamed>' panicked at 'Unexpected interface element node type class_field || {Node class_field (10, 2) - (10, 19)}', libs/wingc/src/parser.rs:691:21
stack backtrace:
RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::h911ba172265603df (wasm://wasm/009bb9ea:wasm-function[237]:0xdcb4a)
    at core::panicking::panic_fmt::h6958314cbbe045b2 (wasm://wasm/009bb9ea:wasm-function[1454]:0x184579)
    at <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::hb89a07c05f53fdae (wasm://wasm/009bb9ea:wasm-function[665]:0x150e7c)
    at <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h69851a1a5d663434 (wasm://wasm/009bb9ea:wasm-function[447]:0x12784a)
    at wingc::parser::Parser::wingit::hdec3ecb17461246e (wasm://wasm/009bb9ea:wasm-function[149]:0xbbc50)
    at wingc_compile (wasm://wasm/009bb9ea:wasm-function[272]:0xe9c0e)
    at wingc_compile.command_export (wasm://wasm/009bb9ea:wasm-function[1600]:0x189aca)
    at Object.invoke (/Users/eyalkeren/.nvm/versions/node/v18.12.1/lib/node_modules/winglang/dist/wingc.js:145:37)
    at compile (/Users/eyalkeren/.nvm/versions/node/v18.12.1/lib/node_modules/winglang/dist/commands/compile.js:125:38)


Internal error: An internal compiler error occurred. Please report this bug by creating an issue on GitHub (github.com/winglang/wing/issues) with your code and this trace.
```

### I expected this:

it shouldn't panic

### Component

Compiler

### Anything else?

I was not able to narrow down the code to see what really is causing the issue 

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Less code, which still yields the same error:
```ts
bring cloud;
bring redis;

interface // this line cause panic

class FibCalculator { 
  mem: redis.Redis;
  init() {
    this.mem = new redis.Redis();  
  }
}
```
We could also remove the `init()` and still get the same error.

**Comment by staycoolcall911** [comment]
Thanks! Closing.
