### ISSUE TITLE
Our hello world example from the getting started guide doesnt compile

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2698]
### I tried this:

Wrote this code from our getting started guide [here](This is the example from here: https://docs.winglang.io/getting-started/hello)
```ts
bring cloud;

let bucket = new cloud.Bucket();
let queue = new cloud.Queue();

queue.addConsumer(inflight (message: str) => {
  bucket.put("wing.txt", "Hello, ${message}");
});
```

then I compiled with this command (also from the guide):
```bash
wing compile --target tf-aws hello.w
```

### This happened:

Got this error:
```
ERROR: Failed to bundle function: ✘ [ERROR] Could not resolve "target/hello.tfaws.781151.tmp/.wing/cloud.queue-addconsumer-e46e5cb7_c85740a2.js"

/Users/shaiber/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/node_modules/esbuild-wasm/lib/main.js:2095
      throw reject;
      ^

Error: Build failed with 1 error:
error: Could not resolve "target/hello.tfaws.781151.tmp/.wing/cloud.queue-addconsumer-e46e5cb7_c85740a2.js"
    at failureErrorWithLog (/Users/shaiber/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/node_modules/esbuild-wasm/lib/main.js:1626:15)
    at /Users/shaiber/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/node_modules/esbuild-wasm/lib/main.js:1038:25
    at /Users/shaiber/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/node_modules/esbuild-wasm/lib/main.js:983:52
    at buildResponseToResult (/Users/shaiber/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/node_modules/esbuild-wasm/lib/main.js:1036:7)
    at /Users/shaiber/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/node_modules/esbuild-wasm/lib/main.js:1065:16
    at responseCallbacks.<computed> (/Users/shaiber/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/node_modules/esbuild-wasm/lib/main.js:687:9)
    at handleIncomingPacket (/Users/shaiber/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/node_modules/esbuild-wasm/lib/main.js:742:9)
    at Socket.readFromStdout (/Users/shaiber/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/node_modules/esbuild-wasm/lib/main.js:663:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: null,
      notes: [],
      pluginName: '',
      text: 'Could not resolve "target/hello.tfaws.781151.tmp/.wing/cloud.queue-addconsumer-e46e5cb7_c85740a2.js"'
    }
  ],
  warnings: []
}

Node.js v18.12.1


target/hello.tfaws.781151.tmp/.wing/preflight.js:46
       const bucket = this.node.root.newAbstract("@winglang/sdk.cloud.Bucket",this,"cloud.Bucket");
       const queue = this.node.root.newAbstract("@winglang/sdk.cloud.Queue",this,"cloud.Queue");
>>     (queue.addConsumer(new $Inflight1(this,"$Inflight1")));
     }
   }
```

### I expected this:

The code to compile

### Component

Compiler

### Wing Version

0.17.42

### Platform(s)

MacOS

### Anything else?

This is the example from here: https://docs.winglang.io/getting-started/hello.
Without the addConsumer part the code compiles

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ShaiBer** [comment]
Version 0.17.40 works, so reverting #2687

**Comment by ShaiBer** [comment]
#2699 fixed it

**Comment by skyrpex** [comment]
I guess it would be worth it adding some e2e tests such as installing wing globally and running some wing examples with verdaccio as the local npm registry...
