### ISSUE TITLE
Unit test in cloud fails with "function returned value of type object, not string"

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#2736]
### I tried this:

```
bring cloud;

let b = new cloud.Bucket();

test "it works" {
  b.put("key", "value");
}
```

Then I ran `wing test -t tf-aws example.w`

### This happened:

```
$ wing test -t tf-aws example.w
✔ Compiling to tf-aws...
✔ terraform init
✔ terraform apply
✔ Setting up test runner...
✔ Running tests...
fail ┌ example.tfaws » root/Default/env0/test:it works
     │ Error: function returned value of type object, not string
     │     at FunctionClient.invoke (/Users/chrisr/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/shared-aws/function.inflight.js:28:19)
     │     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     │     at async TestRunnerClient.runTest (/Users/chrisr/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-tf-aws/test-runner.inflight.js:27:13)
     │     at async /Users/chrisr/.volta/tools/image/packages/winglang/lib/node_modules/winglang/dist/commands/test.js:165:26
     │     at async withSpinner (/Users/chrisr/.volta/tools/image/packages/winglang/lib/node_modules/winglang/dist/util.js:30:24)
     │     at async testTfAws (/Users/chrisr/.volta/tools/image/packages/winglang/lib/node_modules/winglang/dist/commands/test.js:162:21)
     │     at async testOne (/Users/chrisr/.volta/tools/image/packages/winglang/lib/node_modules/winglang/dist/commands/test.js:58:13)
     └     at async test (/Users/chrisr/.volta/tools/image/packages/winglang/lib/node_modules/winglang/dist/commands/test.js:44:9)
One or more tests failed. Cleaning up resources...
✔ terraform destroy
```

### I expected this:

The test shoudl pass

### Is there a workaround?

Add `return "ok"` or any other string to the end of the test block.

### Component

SDK, CLI

### Wing Version

0.18.0

### Node.js Version

18.14.1

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
This doesn't fail anymore. Closing
