### ISSUE TITLE
"foo" is not a function when declaring an inflight class with the same name as a captured preflight class

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2764]
### I tried this:

Test `valid/inflight_class_shadow_preflight_type.w`:

```js
class Goo {
  inflight foo(): num {
    return 42;    
  }
}

let goo = new Goo();

test "access static member" {

  // NOTICE: the name of this inflight class is also Goo
  class Goo {
    bar(): num {
      return 24;
    }
  }

  assert(new Goo().bar() == 24);
  assert(goo.foo() == 42);
}
```

### This happened:

```
fail ┌ inflight_class_shadow_preflight_type.wsim » root/env0/test:access static member
     │ TypeError: goo.foo is not a function
     │     at $Inflight1.handle (/var/folders/vm/cm444l3124j_vh_8rkhz6kqm0000gn/T/wing-bundles-9MORuo/index.js:46:26)
     │     at async exports.handler (/var/folders/vm/cm444l3124j_vh_8rkhz6kqm0000gn/T/wing-bundles-9MORuo/index.js:57:10)
     │     at async Object.withTrace (/Users/eladb/code/wing/libs/wingsdk/lib/testing/simulator.js:71:38)
     │     at async TestRunnerClient.runTest (/Users/eladb/code/wing/libs/wingsdk/lib/target-sim/test-runner.inflight.js:31:13)
     │     at async testSimulator (/Users/eladb/code/wing/apps/wing/dist/commands/test.js:140:22)
     │     at async testOne (/Users/eladb/code/wing/apps/wing/dist/commands/test.js:55:13)
     └     at async test (/Users/eladb/code/wing/apps/wing/dist/commands/test.js:44:9)
```

### I expected this:

To succeed

### Component

Compiler

### Anything else?

I believe this is caused by the capture mechanism, there's some shadowing going on here.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
What if we imposed a rule that variables can be shadowed but types (like classes) cannot be shadowed? (Then, defining an inner class with the same name would be invalid)

**Comment by staycoolcall911** [comment]
This now works
```ts
class Goo {
  pub inflight foo(): num {
    return 42;    
  }
}

let goo = new Goo();

test "access static member" {

  // NOTICE: the name of this inflight class is also Goo
  class Goo {
    pub bar(): num {
      return 24;
    }
  }

  assert(new Goo().bar() == 24);
  assert(goo.foo() == 42);
}
```
