### ISSUE TITLE
Actionable Message for Failed Test Assertion / Test Reports

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#2859]
### Feature Spec

It's easy to identify what the problem for the failed test assertion could be, without having to reach for additional logging statements.

### Use Cases

Given the following test case

```
test "one plus one" {
    let one = 1;
    let other = 1;
    assert(one + other == 3);
}
```

Rather than seeing that that the assertion failed like we do at the moment:

```
fail ┌ main.wsim » root/env1/test:one plus one
Error: assertion failed: '((one + other) === 3)'
    at /var/folders/zl/z8nc41qs7010qsfngfc_z1zc0000gn/T/wing-bundles-T4JNhr/index.js:24:23
    at $Closure6.handle (/var/folders/zl/z8nc41qs7010qsfngfc_z1zc0000gn/T/wing-bundles-T4JNhr/index.js:25:15)...
```

It would be nice to see what the problem is. In this case something along the lines of "expected: 3, actual 2". Could and probably should be inspired by other test frameworks.

### Implementation Notes

This depends on https://github.com/winglang/wing/issues/1977

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skorfmann** [comment]
related to https://github.com/winglang/wing/issues/1977

**Comment by skorfmann** [comment]
This is related https://github.com/winglang/wing/pull/3976

**Comment by staycoolcall911** [comment]
For now we will not improve `assert`. Users are expected to use `expect` instead (pun intended).
I have added a "Decided" section at the top of the issue description to explain that.
