### ISSUE TITLE
Compiler: Failed to Bundle Function when accessing nested Json in assert

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#2911]
### I tried this:

```
bring cloud;

let someData = Json {
    "some": {
        "nested": "data"
    }
};

test "should work" {
    assert("${someData.get("some").get("nested")}" == "data");
}

test "works" {
    log("${someData.get("some").get("nested")}");
}
```

See in [playground](https://play.winglang.io/?code=YnJpbmcgY2xvdWQ7CgpsZXQgc29tZURhdGEgPSBKc29uIHsKICAgICJzb21lIjogewogICAgICAgICJuZXN0ZWQiOiAiZGF0YSIKICAgIH0KfTsKCnRlc3QgInNob3VsZCB3b3JrIiB7CiAgICBhc3NlcnQoIiR7c29tZURhdGEuZ2V0KCJzb21lIikuZ2V0KCJuZXN0ZWQiKX0iID09ICJkYXRhIik7Cn0KCnRlc3QgIndvcmtzIiB7CiAgICBsb2coIiR7c29tZURhdGEuZ2V0KCJzb21lIikuZ2V0KCJuZXN0ZWQiKX0iKTsKfQ==)

### This happened:

```
{
  "success": false,
  "error": "Failed to bundle function: Error: Build failed with 1 error:\ntarget/test.wsim/.wing/inflight.$Closure1.js:11:68: ERROR: Expected \")\" but found \"$\"\n    at failureErrorWithLog (file:///home/httpsplaywinglangio-eqhr/node_modules/\u001b[4mesbuild-wasm\u001b[24m/lib/main.js:1626:15)\n    at eval (file:///home/httpsplaywinglangio-eqhr/node_modules/\u001b[4mesbuild-wasm\u001b[24m/lib/main.js:1038:25)\n    at eval (file:///home/httpsplaywinglangio-eqhr/node_modules/\u001b[4mesbuild-wasm\u001b[24m/lib/main.js:983:52)\n    at buildResponseToResult (file:///home/httpsplaywinglangio-eqhr/node_modules/\u001b[4mesbuild-wasm\u001b[24m/lib/main.js:1036:7)\n    at eval (file:///home/httpsplaywinglangio-eqhr/node_modules/\u001b[4mesbuild-wasm\u001b[24m/lib/main.js:1065:16)\n    at responseCallbacks. (file:///home/httpsplaywinglangio-eqhr/node_modules/\u001b[4mesbuild-wasm\u001b[24m/lib/main.js:687:9)\n    at handleIncomingPacket (file:///home/httpsplaywinglangio-eqhr/node_modules/\u001b[4mesbuild-wasm\u001b[24m/lib/main.js:742:9)\n    at Socket.readFromStdout (file:///home/httpsplaywinglangio-eqhr/node_modules/\u001b[4mesbuild-wasm\u001b[24m/lib/main.js:663:7)\n    at EventEmitter.emit (https://httpsplaywinglangio-eqhr.w-corp.staticblitz.com/blitz.a12d8c69.js:35:156832)\n    at addChunk (https://httpsplaywinglangio-eqhr.w-corp.staticblitz.com/blitz.a12d8c69.js:35:727698) {\n  errors: [\n    {\n      detail: \u001b[90mundefined\u001b[39m,\n      id: \u001b[32m''\u001b[39m,\n      location: \u001b[36m[Object]\u001b[39m,\n      notes: [],\n      pluginName: \u001b[32m''\u001b[39m,\n      text: \u001b[32m'Expected \")\" but found \"$\"'\u001b[39m\n    }\n  ],\n  warnings: []\n}\n"
}
```

### I expected this:

- It allows me to access stringified nested data in `assert`

### Is there a workaround?

the assertion below will work instead:
`assert(str.fromJson(someData.get("some").get("nested")) == "data");`

### Component

Compiler

### Wing Version

v0.20.0

### Node.js Version

v18.16.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
@skorfmann the assertion below will work instead - I added to the workaround section, but of course we also need to fix this bug.
`assert(str.fromJson(someData.get("some").get("nested")) == "data");`

**Comment by staycoolcall911** [comment]
Fixed
