### ISSUE TITLE
TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#3252]
I tried this:

```ts 
bring cloud;
bring http;
let api = new cloud.Api();

inflight class RequestController {
  static inflight handleRequest(request: cloud.ApiRequest): cloud.ApiResponse {
    return cloud.ApiResponse {
      status: 200,
      body: "Hello, world!"
    };
  }
}

api.get("/", inflight (request: cloud.ApiRequest): cloud.ApiResponse => {
  RequestController.handleRequest(request);
});

test "main" {
  let res = http.get(api.url);
  assert( res.body == "Hello, world!");
}
```

I expected this to work, but it didn't 

```
TypeError: Cannot read properties of undefined (reading 'status')
    at isApiResponse (/Users/eyalkeren/.nvm/versions/node/v18.12.1/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-sim/api.inflight.js:108:22)
    at /Users/eyalkeren/.nvm/versions/node/v18.12.1/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-sim/api.inflight.js:49:22
```

**Comment by staycoolcall911** [comment]
The code above is missing a `return` statement on the api.get call. This works:
```ts
bring cloud;
bring http;
let api = new cloud.Api();

inflight class RequestController {
  static inflight handleRequest(request: cloud.ApiRequest): cloud.ApiResponse {
    return cloud.ApiResponse {
      status: 200,
      body: "Hello, world!"
    };
  }
}

api.get("/", inflight (request: cloud.ApiRequest): cloud.ApiResponse => {
  return RequestController.handleRequest(request);
});

test "main" {
  let res = http.get(api.url);
  assert( res.body == "Hello, world!");
}
```
Would have been nice to get a better error message, but that is already covered by #457, so closing this one.
