### ISSUE TITLE
Cannot `wing it` a file residing in WSL2

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#3254]
### I tried this:

Issue related to #2220

`wing it \\wsl.localhost\Ubuntu-22.04\home\user\github\test\hello.w`

### This happened:

```
The Wing Console is running at http://localhost:57721/
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error: EISDIR: illegal operation on a directory, watch '//wsl.localhost/Ubuntu-22.04/home/user/github/test'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2343:34)
    at createFsWatchInstance (C:\Users\[user]\AppData\Roaming\npm\node_modules\winglang\node_modules\@wingconsole\server\dist\index.js:51583:20)
    at setFsWatchListener (C:\Users\[user]\AppData\Roaming\npm\node_modules\winglang\node_modules\@wingconsole\server\dist\index.js:51615:19)
    at NodeFsHandler._watchWithNodeFs (C:\Users\[user]\AppData\Roaming\npm\node_modules\winglang\node_modules\@wingconsole\server\dist\index.js:51736:20)
    at NodeFsHandler._handleDir (C:\Users\[user]\AppData\Roaming\npm\node_modules\winglang\node_modules\@wingconsole\server\dist\index.js:51931:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NodeFsHandler._addToNodeFs (C:\Users\[user]\AppData\Roaming\npm\node_modules\winglang\node_modules\@wingconsole\server\dist\index.js:51977:22)
    at async C:\Users\[user]\AppData\Roaming\npm\node_modules\winglang\node_modules\@wingconsole\server\dist\index.js:52793:27
    at async Promise.all (index 0)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (C:\Users\[user]\AppData\Roaming\npm\node_modules\winglang\node_modules\@wingconsole\server\dist\index.js:52971:16)
    at NodeFsHandler._addToNodeFs (C:\Users\[user]\AppData\Roaming\npm\node_modules\winglang\node_modules\@wingconsole\server\dist\index.js:52003:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\[user]\AppData\Roaming\npm\node_modules\winglang\node_modules\@wingconsole\server\dist\index.js:52793:27
    at async Promise.all (index 0) {
  errno: -4068,
  syscall: 'watch',
  code: 'EISDIR',
  path: '//wsl.localhost/Ubuntu-22.04/home/user/github/test',
  filename: '//wsl.localhost/Ubuntu-22.04/home/user/github/test'
}
```

### I expected this:

I expected Wing Console to work normally.

### Component

Wing Console

### Wing Version

0.23.17

### Node.js Version

18.16.1

### Platform(s)

Windows

### Anything else?

Reference: https://github.com/cypress-io/cypress/issues/21530

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by garysassano** [comment]
No longer relevant since Wing Console got integrated into the VS Code extension.
