### ISSUE TITLE
tests are passing locally but not in ci

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#3402]
### I tried this:

To run the sdk spec tests in ci via its gh action.

### This happened:

Those failed: 

```
Errors:
At counter/peek.w
Error: Invoke failed with message: "Unhandled". Full error: "{"errorType":"AccessDeniedException","errorMessage":"User: arn:aws:sts::***:assumed-role/terraform-20230712225211365100000001/Handler-c818550f is not authorized to perform: dynamodb:GetItem on resource: arn:aws:dynamodb:us-east-1:***:table/wing-counter-cloud.Counter-c8d87bc1 because no identity-based policy allows the dynamodb:GetItem action","trace":["AccessDeniedException: User: arn:aws:sts::***:assumed-role/terraform-20230712225211365100000001/Handler-c818550f is not authorized to perform: dynamodb:GetItem on resource: arn:aws:dynamodb:us-east-1:***:table/wing-counter-cloud.Counter-c8d87bc1 because no identity-based policy allows the dynamodb:GetItem action","    at throwDefaultError (/var/task/index.js:8131:24)","    at /var/task/index.js:8141:40","    at de_GetItemCommandError (/var/task/index.js:11271:18)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async /var/task/index.js:1490:24","    at async /var/task/index.js:5722:22","    at async /var/task/index.js:3623:42","    at async /var/task/index.js:2475:26","    at async CounterClient.peek (/var/task/index.js:26715:24)","    at async $Closure1.handle (/var/task/index.js:49:16)"]}"
    at FunctionClient.invoke (/opt/hostedtoolcache/node/20.4.0/x64/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/shared-aws/function.inflight.js:21:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TestRunnerClient.runTest (/opt/hostedtoolcache/node/20.4.0/x64/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/shared-aws/test-runner.inflight.js:27:13)
    at async /opt/hostedtoolcache/node/20.4.0/x64/lib/node_modules/winglang/dist/commands/test.js:295:30
    at async withSpinner (/opt/hostedtoolcache/node/20.4.0/x64/lib/node_modules/winglang/dist/util.js:55:24)
    at async testTfAws (/opt/hostedtoolcache/node/20.4.0/x64/lib/node_modules/winglang/dist/commands/test.js:292:25)
    at async testOne (/opt/hostedtoolcache/node/20.4.0/x64/lib/node_modules/winglang/dist/commands/test.js:124:20)
    at async Object.test (/opt/hostedtoolcache/node/20.4.0/x64/lib/node_modules/winglang/dist/commands/test.js:54:39)
    at async Command.<anonymous> (/opt/hostedtoolcache/node/20.4.0/x64/lib/node_modules/winglang/dist/cli.js:49:30)
At queue/pop.w
Error: Invoke failed with message: "Unhandled". Full error: "{"errorType":"AccessDenied","errorMessage":"User: arn:aws:sts::***:assumed-role/terraform-20230712231237705400000002/Handler-c893dac8 is not authorized to perform: sqs:sendmessage on resource: arn:aws:sqs:us-east-1:***:cloud-Queue-c86ab873 because no identity-based policy allows the sqs:sendmessage action","trace":["AccessDenied: User: arn:aws:sts::***:assumed-role/terraform-20230712231237705400000002/Handler-c893dac8 is not authorized to perform: sqs:sendmessage on resource: arn:aws:sqs:us-east-1:***:cloud-Queue-c86ab873 because no identity-based policy allows the sqs:sendmessage action","    at throwDefaultError (/var/task/index.js:7359:24)","    at /var/task/index.js:7369:40","    at de_SendMessageCommandError (/var/task/index.js:18374:18)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async /var/task/index.js:1496:24","    at async /var/task/index.js:4950:22","    at async /var/task/index.js:2851:42","    at async /var/task/index.js:20718:20","    at async /var/task/index.js:1703:26","    at async QueueClient.push (/var/task/index.js:21454:9)"]}"
    at FunctionClient.invoke (/opt/hostedtoolcache/node/20.4.0/x64/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/shared-aws/function.inflight.js:21:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TestRunnerClient.runTest (/opt/hostedtoolcache/node/20.4.0/x64/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/shared-aws/test-runner.inflight.js:27:13)
    at async /opt/hostedtoolcache/node/20.4.0/x64/lib/node_modules/winglang/dist/commands/test.js:295:30
    at async withSpinner (/opt/hostedtoolcache/node/20.4.0/x64/lib/node_modules/winglang/dist/util.js:55:24)
    at async testTfAws (/opt/hostedtoolcache/node/20.4.0/x64/lib/node_modules/winglang/dist/commands/test.js:292:25)
    at async testOne (/opt/hostedtoolcache/node/20.4.0/x64/lib/node_modules/winglang/dist/commands/test.js:124:20)
    at async Object.test (/opt/hostedtoolcache/node/20.4.0/x64/lib/node_modules/winglang/dist/commands/test.js:54:39)
    at async Command.<anonymous> (/opt/hostedtoolcache/node/20.4.0/x64/lib/node_modules/winglang/dist/cli.js:49:30)
At website/website.w
Command failed: terraform apply -auto-approve
╷
│ Error: Error putting S3 policy: AccessDenied: Access Denied
│ 	status code: 403, request id: 0FH8BHX5NJRV0B1P, host id: +zkHINNOR2znct99DLuKn6b/8Na2rBcVunAka4lHOvai0APpA7IuwEKHUneF5ePYbq453fjKcMOqlJPMwV4HTFKPZzzoOvlm1pphmAe164o=
│ 
│   with aws_s3_bucket_policy.env0_cloudWebsite_PublicPolicy_67A62A0C,
│   on main.tf.json line 178, in resource.aws_s3_bucket_policy.env0_cloudWebsite_PublicPolicy_67A62A0C:
│  178:       }
│ 
╵

```

in local env (different aws account, same wing version) it worked.

### I expected this:

both to fail or to pass.

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by tsuf239** [comment]
After taking a closer look, it seems like running "tons" of wing files one after another just isn't stable yet- 
each test failed during a different step, and it even passed once,
there are probably steps that are more prone to errors, but I can't tell if that's because of the order of the files or their actual components

![Image](https://github.com/winglang/wing/assets/39455181/946585ad-8809-40d1-ab92-c3fef35c2877)

**Comment by staycoolcall911** [comment]
Fixed.
