### ISSUE TITLE
`Json.stringify` accepts non-Json values

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#3443]
### I tried this:

```
Json.stringify(new cloud.Bucket());
```

### This happened:

```
Error: ERROR: Converting circular structure to JSON
    --> starting at object with constructor 'Bucket'
    |     property 'node' -> object with constructor 'Node'
    --- property 'host' closes the circle

target/test.wsim.004375.tmp/.wing/preflight.js:9
     constructor(scope, id) {
       super(scope, id);
>>     {console.log(((args) => { return JSON.stringify(args[0], null, args[1]) })([this.node.root.newAbstract("@winglang/sdk.cloud.Bucket",this,"cloud.Bucket")]))};
     }
   }

    at Object.compile (/Users/chrisr/.volta/tools/image/packages/winglang/lib/node_modules/winglang/dist/commands/compile.js:117:19)
    at async Command.<anonymous> (/Users/chrisr/.volta/tools/image/packages/winglang/lib/node_modules/winglang/dist/cli.js:48:30)
```

### I expected this:

A compile-time error saying that `Bucket` doesn't match expected type `Json`

### Component

Compiler

### Wing Version

0.24.24

### Node.js Version

18.14.1

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by hasanaburayyan** [comment]
I think this is because of the type union `public static stringify(json: Json | MutJson)` iirc so our jsii_importer recognizes this as any.

**Comment by Chriscbr** [comment]
Mmm I see... I guess the options I see are:
- Separate `Json.stringify` and `MutJson.stringify` methods
- Introduce type unions to the language
- Introduce method overloading to the language
