### ISSUE TITLE
wing compile exception when using utils functions not during inflight

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#3486]
[playground](https://www.winglang.io/play/?code=LwAvACAAVABoAGkAcwAgAGkAcwAgAHQAaABlACAAaQBtAHAAbwByAHQAIABzAHQAYQB0AGUAbQBlAG4AdAAgAGkAbgAgAFcAaQBuAGcALgAKAC8ALwAgAEgAZQByAGUAIAB3AGUAIABiAHIAaQBuAGcAIAB0AGgAZQAgAFcAaQBuAGcAIABzAHQAYQBuAGQAYQByAGQAIABsAGkAYgByAGEAcgB5ACAAdABoAGEAdAAgAAoALwAvACAAYwBvAG4AdABhAGkAbgBzACAAYQBiAHMAdAByAGEAYwB0AGkAbwBuAHMAIABvAGYAIABwAG8AcAB1AGwAYQByACAAYwBsAG8AdQBkACAAcwBlAHIAdgBpAGMAZQBzAC4ACgBiAHIAaQBuAGcAIABjAGwAbwB1AGQAOwAKAGIAcgBpAG4AZwAgAHUAdABpAGwAOwAKAGwAZQB0ACAAYgB1AGMAawBlAHQAIAA9ACAAbgBlAHcAIABjAGwAbwB1AGQALgBCAHUAYwBrAGUAdAAoACkAOwAKAAoAbABlAHQAIABmAG8AdQBuAGQAIAA9ACAAdQB0AGkAbAAuAHcAYQBpAHQAVQBuAHQAaQBsACgAaQBuAGYAbABpAGcAaAB0ACAAKAApADoAIABiAG8AbwBsACAAPQA%2BACAAewAKACAAIABsAG8AZwAoACIAQwBoAGUAYwBrAGkAbgBnACAAaQBmACAAdwBpAG4AZwAuAHQAeAB0ACAAZQB4AGkAcwB0AHMAIgApADsACgAgACAAcgBlAHQAdQByAG4AIABiAHUAYwBrAGUAdAAuAGUAeABpAHMAdABzACgAIgB3AGkAbgBnAC4AdAB4AHQAIgApADsACgB9ACwAIAB1AHQAaQBsAC4AVwBhAGkAdABVAG4AdABpAGwAUAByAG8AcABzACAAewAgAAoAIAAgAHQAaQBtAGUAbwB1AHQAOgAgADEAcwAsAAoAIAAgAGkAbgB0AGUAcgB2AGEAbAA6ACAAMQBtAHMACgB9ACkAOwAgAA%3D%3D)

code example:
```
// This is the import statement in Wing.
// Here we bring the Wing standard library that 
// contains abstractions of popular cloud services.
bring cloud;
bring util;
let bucket = new cloud.Bucket();

let found = util.waitUntil(inflight (): bool => {
  log("Checking if wing.txt exists");
  return bucket.exists("wing.txt");
}, util.WaitUntilProps { 
  timeout: 1s,
  interval: 1ms
}); 
```

**Comment by ainvoner** [comment]
`wing compile -t sim` result:

```
/Users/ainvoner/.nvm/versions/node/v19.3.0/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/util/util.js:53
            if (await f()) {
                      ^

TypeError: f is not a function
    at Util.waitUntil (/Users/ainvoner/.nvm/versions/node/v19.3.0/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/util/util.js:53:23)
    at new $Root (evalmachine.<anonymous>:43:30)
    at new $App (evalmachine.<anonymous>:60:7)
    at evalmachine.<anonymous>:64:1
    at Script.runInContext (node:vm:141:12)
    at Object.runInContext (node:vm:291:6)
    at Object.compile (/Users/ainvoner/.nvm/versions/node/v19.3.0/lib/node_modules/winglang/node_modules/@winglang/compiler/dist/index.js:374:8)
    at async Object.compile (/Users/ainvoner/.nvm/versions/node/v19.3.0/lib/node_modules/winglang/dist/commands/compile.js:48:16)
    at async Command.<anonymous> (/Users/ainvoner/.nvm/versions/node/v19.3.0/lib/node_modules/winglang/dist/cli.js:48:30)

Node.js v19.3.0

```
