### ISSUE TITLE
api.url is not working on aws, wrong WING_TOKEN_TFTOKEN number

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#3539]
### I tried this:

```ts wing
bring cloud;
bring ex;
bring http;
bring util;

let api = new cloud.Api();
// counter to generate uuid
let counter = new cloud.Counter() as "uuid generator";
// our employee database
let db = new ex.Table(
  name: "employees",
  primaryKey: "id",
  columns: {
    "name" => ex.ColumnType.STRING
  }
);

api.get("/employees", inflight (request: cloud.ApiRequest): cloud.ApiResponse => {
  let result = MutJson [];
  let var i = 0;
  for employee in db.list() {
    result.setAt(i, employee);
    i = i + 1;
  }
  return cloud.ApiResponse {
    status: 200,
    body: Json.stringify(result)
  };
});


api.get("/employees/{id}", inflight (request: cloud.ApiRequest): cloud.ApiResponse => {
  let employee = db.get(request.vars.get("id"));
  if let id = employee.tryGet("id") {
    return cloud.ApiResponse {
      status: 200,
      body: Json.stringify(employee)
    };
  }
  return cloud.ApiResponse {
    status: 404
  };
});

api.post("/employees", inflight (request: cloud.ApiRequest): cloud.ApiResponse => {
   if let body = request.body {
    let employeeData = Json.parse(body);
    let id = "${counter.inc()}";
    db.insert(id, employeeData);
    return cloud.ApiResponse {
      status: 201,
      body: id
    };
   }
});

api.put("/employees/{id}", inflight (request: cloud.ApiRequest): cloud.ApiResponse => {
  if let body = request.body {
    let employeeData = Json.parse(body);
    let id = request.vars.get("id");
    try {
      db.update(id, employeeData);
    } catch {
      return cloud.ApiResponse {
        status: 404
      };
    }
    return cloud.ApiResponse {
      status: 200,
      body: Json.stringify(employeeData)
    };
  }
});

api.delete("/employees/{id}", inflight (request: cloud.ApiRequest): cloud.ApiResponse => {
  let id = request.vars.get("id");
  try {
    db.delete(id);
  } catch {
    return cloud.ApiResponse {
      status: 404
    };  
  }
  return cloud.ApiResponse {
    status: 204
  };
});

// TEST Section

inflight class AssertUtils { 
  static assertNumEqual(expected: num? , actual: num?) {
    if expected != actual {
      throw("Assert Error: expected '${expected}' does not equal actual '${actual}'");
    }
    assert(true);
   }

   static assertStringEqual(expected: str? , actual: str?) {
    if expected != actual {
      throw("Assert Error: expected '${expected}' does not equal actual '${actual}'");
    }
    assert(true);
  }

  static assert(b: bool, m: str) {
    if ! b {
      throw(m);
    }
    assert(true);
  }
  static assertJsonEqual(expected: Json, actual: Json) {
    if "${expected}" != "${actual}" {
      throw("Assert Error: expected '${expected}' does not equal actual '${actual}'");
    }
    assert(true);
  }
}

test "get employees should return an empty list" {
  
 if let body = http.get(api.url +  "/employees").body {
  let employees = Json.parse(body); 
  assert(employees.tryGetAt(0) == nil);
 } else {
  assert(false); // should return an empty list
 }
}
```

```sh
wing test rest-api.w -t tf-aws
```

### This happened:

These are the logs from the AWS console

```sh
Test Event Name
(unsaved) test event

Response
{
  "errorType": "SyntaxError",
  "errorMessage": "Unexpected token u in JSON at position 0",
  "trace": [
    "SyntaxError: Unexpected token u in JSON at position 0",
    "    at JSON.parse (<anonymous>)",
    "    at /var/task/index.js:2132:22",
    "    at exports.handler (/var/task/index.js:2141:5)",
    "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1083:29)"
  ]
}

Function Logs
START RequestId: 776a9199-f049-4d0c-a4c8-822972d1871f Version: $LATEST
2023-07-20T08:51:55.942Z	776a9199-f049-4d0c-a4c8-822972d1871f	ERROR	Invoke Error 	{"errorType":"SyntaxError","errorMessage":"Unexpected token u in JSON at position 0","stack":["SyntaxError: Unexpected token u in JSON at position 0","    at JSON.parse (<anonymous>)","    at /var/task/index.js:2132:22","    at exports.handler (/var/task/index.js:2141:5)","    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1083:29)"]}
END RequestId: 776a9199-f049-4d0c-a4c8-822972d1871f
REPORT RequestId: 776a9199-f049-4d0c-a4c8-822972d1871f	Duration: 87.81 ms	Billed Duration: 88 ms	Memory Size: 128 MB	Max Memory Used: 68 MB

Request ID
776a9199-f049-4d0c-a4c8-822972d1871f
```

Notice the code from the lambda is accessing WING_TOKEN_TFTOKEN_TOKEN_**79**
```ts
exports.handler = async function(event) {
  return await (await (async () => {
    const $Closure6Client = require_inflight_Closure6()({
      $api_url: JSON.parse(process.env["WING_TOKEN_TFTOKEN_TOKEN_79"]),
      $http_Util: require_http().Util,
      $std_Json: require_json().Json
    });
    const client = new $Closure6Client({});
    if (client.$inflight_init) {
      await client.$inflight_init();
    }
    return client;
  })()).handle(event);
};
```

While the environment variable is WING_TOKEN_TFTOKEN_TOKEN_**77**
```
WING_FUNCTION_NAME = Handler-c8b4493e
WING_TARGET = tf-aws
WING_TOKEN_TFTOKEN_TOKEN_77 = "https://le9lq40tn2.execute-api.us-east-1.amazonaws.com/prod"
```

### I expected this:

to work

### Is there a workaround?

assign the `api.url` variable once in preflight 

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by tsuf239** [comment]
fixed by #3772
