### ISSUE TITLE
Itermittant queue spec test permission failure

### ISSUE THREAD

**Issue by MarkMcCulloh** [winglang/wing#3897]
### I tried this:

See https://github.com/winglang/wing/actions/runs/5917587426/job/16046054892

### This happened:

```
fail ┌ pop.tfaws » root/Test.NUImFLl7-D/env0/test:pop
     │ Error: Invoke failed with message: "Unhandled". Full error: "{"errorType":"Error","errorMessage":"assertion failed: first == \"Foo\"","trace":["Error: assertion failed: first == \"Foo\"","    at /var/task/index.js:52:23","    at $Closure1.handle (/var/task/index.js:53:15)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async exports.handler (/var/task/index.js:21513:10)"]}"
```

### I expected this:

Always pass

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
@MarkMcCulloh Is there an error in AWS related to permissions specifically?

**Comment by MarkMcCulloh** [comment]
https://github.com/winglang/wing/actions/runs/6028244874/job/16355140792

```
Invoke failed with message: "Unhandled". Full error: "{"errorType":"Error","errorMessage":"AccessDenied: User: arn:aws:sts::***:assumed-role/terraform-20230830174630552300000002/Handler-c89be899 is not authorized to perform: sqs:sendmessage on resource: arn:aws:sqs:us-east-1:***:cloud-Queue-c80829e3 because no identity-based policy allows the sqs:sendmessage action\n    at throwDefaultError (/var/task/index.js:8155:24)\n    at /var/task/index.js:8165:40\n    at de_SendMessageCommandError (/var/task/index.js:28197:18)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /var/task/index.js:1514:24\n    at async /var/task/index.js:5746:22\n    at async /var/task/index.js:3647:42\n    at async /var/task/index.js:30541:20\n    at async /var/task/index.js:2499:26\n    at async /var/task/index.js:31279:13","trace":["Error: AccessDenied: User: arn:aws:sts::***:assumed-role/terraform-20230830174630552300000002/Handler-c89be899 is not authorized to perform: sqs:sendmessage on resource: arn:aws:sqs:us-east-1:***:cloud-Queue-c80829e3 because no identity-based policy allows the sqs:sendmessage action","    at throwDefaultError (/var/task/index.js:8155:24)","    at /var/task/index.js:8165:40","    at de_SendMessageCommandError (/var/task/index.js:28197:18)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async /var/task/index.js:1514:24","    at async /var/task/index.js:5746:22","    at async /var/task/index.js:3647:42","    at async /var/task/index.js:30541:20","    at async /var/task/index.js:2499:26","    at async /var/task/index.js:31279:13","    at /var/task/index.js:31284:19","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async Promise.all (index 0)","    at async QueueClient.push (/var/task/index.js:31287:9)","    at async $Closure2.handle (/var/task/index.js:45:11)","    at async exports.handler (/var/task/index.js:36656:10)"]}"
```

**Comment by Chriscbr** [comment]
Ahh I see, yeah I missed that one. It looks like two tests are flaking, `queue/set_consumer.w` and `queue/pop.w`.

I'm wondering if the error in `pop.w` could just be timing related (for example, maybe calling `pop` immediately after `push` on an SQS queue is flaking because it takes time for the storage nodes to be updated -- I'm not sure if it's transactional)

**Comment by garysassano** [comment]
@MarkMcCulloh @Chriscbr The old code wasn't causing any flaking? See #3875

It's not clear to me what difference may be causing the test to flake.

**Comment by garysassano** [comment]
The error is about Terraform user not having the permission to push to the queue, so it's entirely related to the first line of code inside the test: `q.push("Foo", "Bar");`

**Comment by staycoolcall911** [comment]
@MarkMcCulloh is that still happening?

**Comment by MarkMcCulloh** [comment]
Yeah this is still happening (see failure here https://github.com/winglang/wing/actions/runs/6881460035/job/18717927296)
