### ISSUE TITLE
inflight init not called when accessing nested preflight fields

### ISSUE THREAD

**Issue by yoav-steinberg** [winglang/wing#3979]
### I tried this:

```wing
bring cloud;

class Foo {
  pub b: cloud.Bucket;

  new() {
    this.b = new cloud.Bucket();
  }

  inflight new() {
    this.b.put("hello.txt", "world");
  }
}

let foo = new Foo();

test "test" {
  log(foo.b.get("hello.txt"));
}
```

### This happened:

```
fail ┌ bla.wsim » root/env0/test:test
     │ Error: Object does not exist (key=hello.txt): Error: ENOENT: no such file or directory, open '/tmp/wing-sim-mzY1NR/acec329f80cc50edbab0dfbc2283d427ac673f84e6d8b949101791867b9b7771a53d2ffb1f8386189227beed4395b9a78171a1349700e2885c70ae14358d72ff'
     │     at Object.activity (/home/yoav/wing2/libs/wingsdk/lib/target-sim/bucket.inflight.js:104:27)
     │     at async Object.withTrace (/home/yoav/wing2/libs/wingsdk/lib/testing/simulator.js:256:34)
     │     at async $Closure1.handle (/tmp/wing-bundles-sJpWpl/index.js:18:25)
     │     at async exports.handler (/tmp/wing-bundles-sJpWpl/index.js:29:10)
     │     at async Object.withTrace (/home/yoav/wing2/libs/wingsdk/lib/testing/simulator.js:256:34)
     │     at async TestRunnerClient.runTest (/home/yoav/wing2/libs/wingsdk/lib/target-sim/test-runner.inflight.js:31:13)
     │     at async testSimulator (/home/yoav/wing2/apps/wing/dist/commands/test.js:214:22)
     │     at async testOne (/home/yoav/wing2/apps/wing/dist/commands/test.js:125:20)
     │     at async testFile (/home/yoav/wing2/apps/wing/dist/commands/test.js:55:39)
     │     at async Promise.all (index 0)
     │     at async Object.test (/home/yoav/wing2/apps/wing/dist/commands/test.js:66:5)
     └     at async Command.<anonymous> (/home/yoav/wing2/apps/wing/dist/cli.js:46:30)
 
 
Tests 1 failed (1)
Test Files 1 failed (1)
Duration 0m0.26s
```

### I expected this:

to print "world"

### Is there a workaround?

move the initialization logic to some other inflight method and call it before using the class:
```
test "test" {
  foo.do_init();
  log(foo.b.get("hello.txt"));
}
```

### Component

Compiler

### Anything else?

This is a result of of the lifting logic. Since we explicitly lift the preflight  `foo.b` expression and we never actually just lift `foo`, `foo`'s inflight init is never called.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by yoav-steinberg** [comment]
When discussing this with @Chriscbr, he mentioned that it might not be expected that the inflight init of `foo` will be called. Imagine this:
```wing
bring cloud;

class Foo {
  b: cloud.Bucket;

  init() {
    this.b = new cloud.Bucket();
  }

  inflight init() {
    this.b.put("hello.txt", "world");
  }
}

let foo = new Foo();
let b = foo.b;

test "test" {
  log(b.get("hello.txt"));
}
```

Here there's no mention of `foo` inflight. So the user might not even expect for `foo`'s inflight `init` to be called. 
Generally speaking this is a result of poorly written code. Ideally you'd have some access method on `b` and never access it directly:
```wing
// inflight code
log(foo.read_b("hello.txt"));
```
In this :point_up: case the compiler will "lift" foo explicitly and therefore the inflight init will be called. So when writing idiomatic code the inflight init will be executed. Worth considering if this is a bug or not, and thinking of a way to gain some clarity about inflight inits.

**Comment by Shahmanch98** [comment]
> ### I tried this:
> 
> ```wing
> 
> bring cloud;
> 
> 
> 
> class Foo {
> 
>   b: cloud.Bucket;
> 
> 
> 
>   init() {
> 
>     this.b = new cloud.Bucket();
> 
>   }
> 
> 
> 
>   inflight init() {
> 
>     this.b.put("hello.txt", "world");
> 
>   }
> 
> }
> 
> 
> 
> let foo = new Foo();
> 
> 
> 
> test "test" {
> 
>   log(foo.b.get("hello.txt"));
> 
> }
> 
> ```
> 
> ### This happened:
> 
> ```
> 
> fail ┌ bla.wsim » root/env0/test:test
> 
>      │ Error: Object does not exist (key=hello.txt): Error: ENOENT: no such file or directory, open '/tmp/wing-sim-mzY1NR/acec329f80cc50edbab0dfbc2283d427ac673f84e6d8b949101791867b9b7771a53d2ffb1f8386189227beed4395b9a78171a1349700e2885c70ae14358d72ff'
> 
>      │     at Object.activity (/home/yoav/wing2/libs/wingsdk/lib/target-sim/bucket.inflight.js:104:27)
> 
>      │     at async Object.withTrace (/home/yoav/wing2/libs/wingsdk/lib/testing/simulator.js:256:34)
> 
>      │     at async $Closure1.handle (/tmp/wing-bundles-sJpWpl/index.js:18:25)
> 
>      │     at async exports.handler (/tmp/wing-bundles-sJpWpl/index.js:29:10)
> 
>      │     at async Object.withTrace (/home/yoav/wing2/libs/wingsdk/lib/testing/simulator.js:256:34)
> 
>      │     at async TestRunnerClient.runTest (/home/yoav/wing2/libs/wingsdk/lib/target-sim/test-runner.inflight.js:31:13)
> 
>      │     at async testSimulator (/home/yoav/wing2/apps/wing/dist/commands/test.js:214:22)
> 
>      │     at async testOne (/home/yoav/wing2/apps/wing/dist/commands/test.js:125:20)
> 
>      │     at async testFile (/home/yoav/wing2/apps/wing/dist/commands/test.js:55:39)
> 
>      │     at async Promise.all (index 0)
> 
>      │     at async Object.test (/home/yoav/wing2/apps/wing/dist/commands/test.js:66:5)
> 
>      └     at async Command.<anonymous> (/home/yoav/wing2/apps/wing/dist/cli.js:46:30)
> 
>  
> 
>  
> 
> Tests 1 failed (1)
> 
> Test Files 1 failed (1)
> 
> Duration 0m0.26s
> 
> ```
> 
> ### I expected this:
> 
> to print "world"
> 
> ### Is there a workaround?
> 
> move the initialization logic to some other inflight method and call it before using the class:
> 
> ```
> 
> test "test" {
> 
>   foo.do_init();
> 
>   log(foo.b.get("hello.txt"));
> 
> }
> 
> ```
> 
> ### Component
> 
> Compiler
> 
> ### Wing Version
> 
> _No response_
> 
> ### Node.js Version
> 
> _No response_
> 
> ### Platform(s)
> 
> _No response_
> 
> ### Anything else?
> 
> This is a result of of the lifting logic. Since we explicitly lift the preflight  `foo.b` expression and we never actually just lift `foo`, `foo`'s inflight init is never called.
> 
> ### Community Notes
> 
> 
> 
> * Please vote by adding a 👍 reaction to the issue to help us prioritize.
> 
> * If you are interested to work on this issue, please leave a comment.
> 
>

**Comment by yoav-steinberg** [comment]
@Shahmanch98 you wanted to comment on this issue?

**Comment by staycoolcall911** [comment]
Related to $4564

**Comment by ekeren** [comment]
> Related to $4564

Related to #4564

**Comment by staycoolcall911** [comment]
Still happens. I modernized the original code sample to Wing 0.59.13
