### ISSUE TITLE
Using `aws-sdk` in extern JS raises "attachOn.addNamedListener is not a function"

### ISSUE THREAD

**Issue by eladb** [winglang/wing#4175]
### I tried this:

```sh
$ npm i aws-sdk
```

`util.js`

```js
require('aws-sdk');
```

`main.w`

```js
class Util {
  extern "./util.js" static inflight load_sdk();
}

test "aws-sdk" {
  Util.load_sdk();
}
```

Run:

```sh
wing test main.w
```

### This happened:

```
fail ┌ main.wsim » root/env0/test:aws-sdk
     │ TypeError: attachOn.addNamedListener is not a function
     │     at Function.addDefaultMonitoringListeners (/var/folders/vm/cm444l3124j_vh_8rkhz6kqm0000gn/T/wing-bundles-RTzvIC/index.js:4481:18)
     │     at Function.defineService (/var/folders/vm/cm444l3124j_vh_8rkhz6kqm0000gn/T/wing-bundles-RTzvIC/index.js:4411:22)
     │     at node_modules/aws-sdk/clients/sts.js (/var/folders/vm/cm444l3124j_vh_8rkhz6kqm0000gn/T/wing-bundles-RTzvIC/index.js:12512:24)
     │     at __require (/var/folders/vm/cm444l3124j_vh_8rkhz6kqm0000gn/T/wing-bundles-RTzvIC/index.js:4:50)
     │     at node_modules/aws-sdk/lib/credentials/temporary_credentials.js (/var/folders/vm/cm444l3124j_vh_8rkhz6kqm0000gn/T/wing-bundles-RTzvIC/index.js:12530:15)
     │     at __require (/var/folders/vm/cm444l3124j_vh_8rkhz6kqm0000gn/T/wing-bundles-RTzvIC/index.js:4:50)
     │     at node_modules/aws-sdk/lib/node_loader.js (/var/folders/vm/cm444l3124j_vh_8rkhz6kqm0000gn/T/wing-bundles-RTzvIC/index.js:22018:5)
     │     at __require (/var/folders/vm/cm444l3124j_vh_8rkhz6kqm0000gn/T/wing-bundles-RTzvIC/index.js:4:50)
     │     at node_modules/aws-sdk/lib/aws.js (/var/folders/vm/cm444l3124j_vh_8rkhz6kqm0000gn/T/wing-bundles-RTzvIC/index.js:763821:5)
     └     at __require (/var/folders/vm/cm444l3124j_vh_8rkhz6kqm0000gn/T/wing-bundles-RTzvIC/index.js:4:50)
 
 
Tests 1 failed (1)
Test Files 1 failed (1)
Duration 0m4.93s
```

### I expected this:

To work

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by rainiersvn** [comment]
@eladb, I was able to get my wing project to a point where I can either use extern aws-sdk or extern js_code syntaxt, but both of them result in the `TypeError: attachOn.addNamedListener is not a function`.

Do you know what is causing this? Is there  a workaround for this atm?

**Comment by eladb** [comment]
Have you seen this?

https://github.com/rainiersvn/wing-projects/pull/1

**Comment by rainiersvn** [comment]
Hey Elab, yes. Thanks so much, loving the dev community vibes!

**Comment by Chriscbr** [comment]
I've tried the example and it looks like it's working now (Wing 0.64.4). Closing

```js
// util.js
exports.load_sdk = function() {
    require('aws-sdk');
}

// main.w
class Util {
  pub extern "./util.js" static inflight load_sdk();
}

test "aws-sdk" {
  Util.load_sdk();
}
```
