### ISSUE TITLE
Compiler bug during type-checking: property and method with the same name

### ISSUE THREAD

**Issue by eladb** [winglang/wing#4586]
### I tried this:

```js
class Foo {
  x: str;
  x() { }
}
```

### This happened:

```
Failed to compile.

error: Symbol "x" already defined in this scope
  --> wing/main.w:3:3
  |
2 |   x: str;
  |   - previous definition
3 |   x() { }
  |   ^ Symbol "x" already defined in this scope


error: Preflight field "x" is not initialized
  --> wing/main.w:2:3
  |
2 |   x: str;
  |   ^ Preflight field "x" is not initialized


error: Compiler bug during type-checking ('panicked at libs/wingc/src/type_check.rs:4310:14:
Expected method type to be a function signature'), please report at https://www.winglang.io/contributing/start-here/bugs
  --> wing/main.w:1:1
  |  
1 | / class Foo {
2 | |   x: str;
3 | |   x() { }
4 | | }
  | \-^ Compiler bug during type-checking ('panicked at libs/wingc/src/type_check.rs:4310:14:
Expected method type to be a function signature'), please report at https://www.winglang.io/contributing/start-here/bugs

```

### I expected this:

To get a reasonable error message

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Duplicates #1635
