### ISSUE TITLE
Property 'closeAllConnections' does not exist on type 'Server<typeof IncomingMessage, typeof ServerResponse>'

### ISSUE THREAD

**Issue by supasaf** [winglang/wing#4751]
### I tried this:

I just cloned the project, and run:

```
❯ pnpm build

> @winglang/monorepo@ build /Users/ss/Downloads/wing
> turbo compile post-compile lint eslint test package
...
@wingconsole/server:compile: src/index.ts(254,16): error TS2339: Property 'closeAllConnections' does not exist on type 'Server<typeof IncomingMessage, typeof ServerResponse>'.
@wingconsole/server:compile:
@wingconsole/server:compile: RollupError: Failed to compile. Check the logs above.
@wingconsole/server:compile:     at error (/Users/ss/Downloads/wing/node_modules/.pnpm/registry.npmmirror.com+rollup@3.29.4/node_modules/rollup/dist/shared/rollup.js:353:30)
@wingconsole/server:compile:     at Object.error (/Users/ss/Downloads/wing/node_modules/.pnpm/registry.npmmirror.com+rollup@3.29.4/node_modules/rollup/dist/shared/rollup.js:1721:20)
@wingconsole/server:compile:     at Object.error (/Users/ss/Downloads/wing/node_modules/.pnpm/registry.npmmirror.com+rollup@3.29.4/node_modules/rollup/dist/shared/rollup.js:25627:42)
@wingconsole/server:compile:     at generateDtsFromTs (/Users/ss/Downloads/wing/node_modules/.pnpm/registry.npmmirror.com+tsup@6.7.0_postcss@8.4.31_typescript@5.2.2/node_modules/tsup/dist/rollup.js:7498:22)
@wingconsole/server:compile:     at /Users/ss/Downloads/wing/node_modules/.pnpm/registry.npmmirror.com+tsup@6.7.0_postcss@8.4.31_typescript@5.2.2/node_modules/tsup/dist/rollup.js:7505:59
@wingconsole/server:compile:     at _nullishCoalesce (/Users/ss/Downloads/wing/node_modules/.pnpm/registry.npmmirror.com+tsup@6.7.0_postcss@8.4.31_typescript@5.2.2/node_modules/tsup/dist/rollup.js:1:198)
@wingconsole/server:compile:     at Object.transform (/Users/ss/Downloads/wing/node_modules/.pnpm/registry.npmmirror.com+tsup@6.7.0_postcss@8.4.31_typescript@5.2.2/node_modules/tsup/dist/rollup.js:7505:18)
@wingconsole/server:compile:     at /Users/ss/Downloads/wing/node_modules/.pnpm/registry.npmmirror.com+rollup@3.29.4/node_modules/rollup/dist/shared/rollup.js:1914:40
@wingconsole/server:compile: Error: error occured in dts build
@wingconsole/server:compile:     at Worker.<anonymous> (/Users/ss/Downloads/wing/node_modules/.pnpm/registry.npmmirror.com+tsup@6.7.0_postcss@8.4.31_typescript@5.2.2/node_modules/tsup/dist/index.js:2281:26)
@wingconsole/server:compile:     at Worker.emit (node:events:514:28)
@wingconsole/server:compile:     at MessagePort.<anonymous> (node:internal/worker:243:53)
@wingconsole/server:compile:     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:741:20)
@wingconsole/server:compile:     at exports.emitMessage (node:internal/per_context/messageport:23:28)
@wingconsole/server:compile: DTS Build error
@wingconsole/server:compile:  ELIFECYCLE  Command failed with exit code 1.
@wingconsole/server:compile: ERROR: command finished with error: command (/Users/ss/Downloads/wing/apps/wing-console/console/server) pnpm run compile exited (1)
@winglang/sdk:package: cache miss, executing 16c95872b3834647
@wingconsole/server#compile: command (/Users/ss/Downloads/wing/apps/wing-console/console/server) pnpm run compile exited (1)

 Tasks:    39 successful, 45 total
Cached:    5 cached, 45 total
  Time:    46.647s
Failed:    @wingconsole/server#compile

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
```

### This happened:

build failed

### I expected this:

build success

### Component

Tutorial

### Node.js Version

v18.17.1

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by supasaf** [comment]
Not fix that,

```
❯ history
 1035  cd wing
 ...
 1048  git clean -fdx
 1049  pnpm i
 1050  pnpm build --force
```

And output:

```
@winglang/sdk:test:  ✓ test/fs/fs.test.ts  (5 tests) 16ms
@wingconsole/server:compile: src/index.ts(254,16): error TS2339: Property 'closeAllConnections' does not exist on type 'Server<typeof IncomingMessage, typeof ServerResponse>'.
@wingconsole/server:compile:
@wingconsole/server:compile: Error: error occured in dts build
@wingconsole/server:compile:     at Worker.<anonymous> (/Users/ss/Downloads/wing/node_modules/.pnpm/registry.npmmirror.com+tsup@6.7.0_postcss@8.4.31_typescript@5.2.2/node_modules/tsup/dist/index.js:2281:26)
@wingconsole/server:compile:     at Worker.emit (node:events:514:28)
@wingconsole/server:compile:     at MessagePort.<anonymous> (node:internal/worker:243:53)
@wingconsole/server:compile:     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:741:20)
@wingconsole/server:compile:     at exports.emitMessage (node:internal/per_context/messageport:23:28)
@wingconsole/server:compile: DTS Build error
@wingconsole/server:compile: RollupError: Failed to compile. Check the logs above.
@wingconsole/server:compile:     at error (/Users/ss/Downloads/wing/node_modules/.pnpm/registry.npmmirror.com+rollup@3.29.4/node_modules/rollup/dist/shared/rollup.js:353:30)
@wingconsole/server:compile:     at Object.error (/Users/ss/Downloads/wing/node_modules/.pnpm/registry.npmmirror.com+rollup@3.29.4/node_modules/rollup/dist/shared/rollup.js:1721:20)
@wingconsole/server:compile:     at Object.error (/Users/ss/Downloads/wing/node_modules/.pnpm/registry.npmmirror.com+rollup@3.29.4/node_modules/rollup/dist/shared/rollup.js:25627:42)
@wingconsole/server:compile:     at generateDtsFromTs (/Users/ss/Downloads/wing/node_modules/.pnpm/registry.npmmirror.com+tsup@6.7.0_postcss@8.4.31_typescript@5.2.2/node_modules/tsup/dist/rollup.js:7498:22)
@wingconsole/server:compile:     at /Users/ss/Downloads/wing/node_modules/.pnpm/registry.npmmirror.com+tsup@6.7.0_postcss@8.4.31_typescript@5.2.2/node_modules/tsup/dist/rollup.js:7505:59
@wingconsole/server:compile:     at _nullishCoalesce (/Users/ss/Downloads/wing/node_modules/.pnpm/registry.npmmirror.com+tsup@6.7.0_postcss@8.4.31_typescript@5.2.2/node_modules/tsup/dist/rollup.js:1:198)
@wingconsole/server:compile:     at Object.transform (/Users/ss/Downloads/wing/node_modules/.pnpm/registry.npmmirror.com+tsup@6.7.0_postcss@8.4.31_typescript@5.2.2/node_modules/tsup/dist/rollup.js:7505:18)
@wingconsole/server:compile:     at /Users/ss/Downloads/wing/node_modules/.pnpm/registry.npmmirror.com+rollup@3.29.4/node_modules/rollup/dist/shared/rollup.js:1914:40
@wingconsole/server:compile:  ELIFECYCLE  Command failed with exit code 1.
@wingconsole/server:compile: ERROR: command finished with error: command (/Users/ss/Downloads/wing/apps/wing-console/console/server) pnpm run compile exited (1)
@wingconsole/server#compile: command (/Users/ss/Downloads/wing/apps/wing-console/console/server) pnpm run compile exited (1)

 Tasks:    40 successful, 44 total
Cached:    0 cached, 44 total
  Time:    1m38.856s
Failed:    @wingconsole/server#compile

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.

```

**Comment by staycoolcall911** [comment]
Ok, thanks for giving it a try.
Let's try a couple more things:
1. Can you please let me know the output you get for `npm list -g`?
2. Please use `nvm` or a different tool to install Node v18.16.0, then try again `git clean -fdx`, `pnpm i`, `pnpm build --force`.

**Comment by supasaf** [comment]
Thanks, will try 18.16.0:)

The current output is:

```
❯ npm list -g
/Users/ss/.nvm/versions/node/v18.17.1/lib
├── aws-sdk@2.1457.0
├── corepack@0.18.0
├── npm@9.6.7
├── typescript@5.2.2
└── wabt@1.0.32
```

**Comment by supasaf** [comment]
Sounds good for me right now:

```
angar:test:
hangar:test:   Snapshots  1 updated
hangar:test:  Test Files  234 passed (234)
hangar:test:       Tests  555 passed (555)
hangar:test:    Start at  22:06:07
hangar:test:    Duration  179.23s (transform 1.44s, setup 4ms, collect 2.33s, tests 1432.58s, environment 5ms, prepare 620ms)
```

Awesome thanks @staycoolcall911

**Comment by staycoolcall911** [comment]
Glad it worked @supasaf!
