### ISSUE TITLE
Unable to extend jsii classes, such as`cdk8s.Chart` in non-entrypoint files

### ISSUE THREAD

**Issue by eladb** [winglang/wing#4791]
### I tried this:

I am trying to write a module (non-entrypoint) with the following code:

```js
bring "cdk8s" as cdk8s;

class Foo extends cdk8s.Chart { }
```

### This happened:

```
ERROR: Cannot read properties of undefined (reading 'node')

test/target/test/containers.test.wsim.202680.tmp/.wing/preflight.js:6
   const $wing_is_test = process.env.WING_IS_TEST === "true";
   const std = $stdlib.std;
>> const containers = require("./preflight.containers-12.js")({ $stdlib });
   const expect = $stdlib.expect;
   const http = $stdlib.http;

--------------------------------- STACK TRACE ---------------------------------
/Users/eladb/code/containers/test/target/test/containers.test.wsim.202680.tmp/.wing/preflight.workload-10.js:70
  class _Chart extends (this.node.root.typeForFqn("cdk8s.Chart") ?? cdk8s.Chart) {
                             ^

TypeError: Cannot read properties of undefined (reading 'node')
    at module.exports (/Users/eladb/code/containers/test/target/test/containers.test.wsim.202680.tmp/.wing/preflight.workload-10.js:70:30)
    at module.exports (/Users/eladb/code/containers/test/target/test/containers.test.wsim.202680.tmp/.wing/preflight.tfaws-11.js:5:45)
    at module.exports (/Users/eladb/code/containers/test/target/test/containers.test.wsim.202680.tmp/.wing/preflight.containers-12.js:6:49)
    at evalmachine.<anonymous>:7:59
    at Script.runInContext (node:vm:135:12)
    at Object.runInContext (node:vm:283:6)
    at runPreflightCodeInVm (/Users/eladb/code/containers/node_modules/@winglang/compiler/dist/index.js:464:8)
    at async Object.compile (/Users/eladb/code/containers/node_modules/@winglang/compiler/dist/index.js:401:5)
    at async compile (/Users/eladb/code/containers/node_modules/winglang/dist/commands/compile.js:63:16)
    at async testOne (/Users/eladb/code/containers/node_modules/winglang/dist/commands/test/test.js:115:22)
    at async testFile (/Users/eladb/code/containers/node_modules/winglang/dist/commands/test/test.js:77:39)
    at async Promise.all (index 0)
    at async Object.test (/Users/eladb/code/containers/node_modules/winglang/dist/commands/test/test.js:96:5)
    at async Command.<anonymous> (/Users/eladb/code/containers/node_modules/winglang/dist/cli.js:47:30)
 
 ```

### I expected this:

To work

### Is there a workaround?

Yes, you can declare the class inside another preflight class:

```js
class MyPreflightClass {
  init() {
    class MyChart extends cdk8s.Chart {}
  }
}
```

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
Related to https://github.com/winglang/wing/issues/3717

**Comment by eladb** [comment]
@staycoolcall911 changed to p1

**Comment by Chriscbr** [comment]
@hasanaburayyan asked if I had any thoughts on how to go about supporting these kinds of parent super classes. This is a pretty tricky issue, so I'm not sure what will work best. But I'll throw some ideas into the ring:

Idea 1: change the compiler's code generation for non-entrypoint files so that the $root or $app or $platform etc. is everywhere. So instead of emitting:

```js
// preflight.foo.js
class Foo extends this.node.root.app.tryGetFqn("cdk8s.Chart") ?? cdk8s.Chart {
  // ...
}
module.exports = { Foo }
```

We might emit

```js
// preflight.foo.js
module.exports = function($app) {
  class Foo extends $root.app.tryGetFqn("cdk8s.Chart") ?? cdk8s.Chart {
    // ...
  }
  return { Foo };
}
```

Call sites where `preflight.foo.js` is `require()`-ed would also have to get updated.

Idea 2: allow everything to be defined using the old classes (or placeholders) as the parent classes, and then have the compiler generate code for all classes that have extended `cdk8s.Chart`, to dynamically change their parent class after-the-fact by mutating the JavaScript prototype chain.

Here's some working JS that shows how it might work, though I've heard modifying JavaScript prototype chains can be risky.

```js
// platform.js
class CustomBucketBase {
    constructor(name) {
        this.name = name;
    }
    greet() {
        console.log(`Hello, ${this.name} from CustomBucketBase`);
    }
}

class Platform {
    static getType(fqn) {
        if (fqn === "BucketBase") {
            return CustomBucketBase;
        }
    }
}

exports.Platform = Platform;

// index.js
const { Platform } = require('./platform');

class BucketBase {
    constructor(name) {
        this.name = name;
    }
    greet() {
        console.log(`Hello, ${this.name} from BucketBase`);
    }
}

class MyBucket extends BucketBase {
    constructor(name) {
        super(name);
    }
}

function overrideParent(subClass, superClass) {
    Object.setPrototypeOf(subClass.prototype, superClass.prototype);
    subClass.__proto__ = superClass;
}

const $CustomBucketBase = Platform.getType("BucketBase");
overrideParent(MyBucket, $CustomBucketBase);

const bucket = new MyBucket("my-bucket");
console.log(bucket instanceof BucketBase); // false
console.log(bucket instanceof $CustomBucketBase); // true
bucket.greet(); // Hello, my-bucket from CustomBucketBase
```

**Comment by hasanaburayyan** [comment]
Closing this issue in favor of: https://github.com/winglang/wing/issues/6093

**Comment by eladb** [comment]
I think an `$app` or `$root` global is a good approach
