### ISSUE TITLE
Stacktrace shows uninteresting source context

### ISSUE THREAD

**Issue by MarkMcCulloh** [winglang/wing#4957]
### I tried this:

Received this error:

```
fail ┌ pop.test.tfaws.817246 » root/Test.hWoygpihMz/env0/test:pop
     │ runtime error: AccessDenied: User: arn:aws:sts::***:assumed-role/terraform-20231115184406706200000001/Handler-c814f0c7 is not authorized to perform: sqs:sendmessage on resource: arn:aws:sqs:us-east-1:***:cloud-Queue-c80[116](https://github.com/winglang/wing/actions/runs/6881460035/job/18717927296#step:11:117)e0 because no identity-based policy allows the sqs:sendmessage action
     │   --> localwing/node_modules/@winglang/sdk/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22
     │   | const throwDefaultError = (*** output, parsedBody, exceptionCtor, errorCode ***) => ***
     │   |     const $metadata = deserializeMetadata(output);
     │   |     const statusCode = $metadata.httpStatusCode ? $metadata.httpStatusCode + "" : undefined;
     │ 8 |     const response = new exceptionCtor(***
     │   |                      ^
     │ at throwDefaultError (/home/runner/work/wing/wing/localwing/node_modules/@winglang/sdk/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)
     │ at (/home/runner/work/wing/wing/localwing/node_modules/@winglang/sdk/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:21)
     │ at de_SendMessageCommandError (/home/runner/work/wing/wing/localwing/node_modules/@winglang/sdk/node_modules/@aws-sdk/client-sqs/dist-cjs/protocols/Aws_json1_0.js:1072:20)
     │ at processTicksAndRejections (node:internal/process/task_queues:95:5)
     │ at (/home/runner/work/wing/wing/localwing/node_modules/@winglang/sdk/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24)
     │ at (/home/runner/work/wing/wing/localwing/node_modules/@winglang/sdk/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20)
     │ at (/home/runner/work/wing/wing/localwing/node_modules/@winglang/sdk/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46)
     │ at (/home/runner/work/wing/wing/localwing/node_modules/@winglang/sdk/node_modules/@aws-sdk/middleware-sdk-sqs/dist-cjs/send-message.js:7:18)
     │ at (/home/runner/work/wing/wing/localwing/node_modules/@winglang/sdk/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26)
     │ at (/home/runner/work/wing/wing/examples/tests/sdk_tests/queue/target/test/pop.test.tfaws/.wing/../../../../../../../../localwing/node_modules/@winglang/sdk/src/shared-aws/queue.inflight.ts:28:9)
     │ at (/home/runner/work/wing/wing/examples/tests/sdk_tests/queue/target/test/pop.test.tfaws/.wing/../../../../../../../../localwing/node_modules/@winglang/sdk/src/shared-aws/queue.inflight.ts:37:15)
     │ at processTicksAndRejections (node:internal/process/task_queues:95:5)
     │ at all (:undefined:undefined)
     │ at push (/home/runner/work/wing/wing/examples/tests/sdk_tests/queue/target/test/pop.test.tfaws/.wing/../../../../../../../../localwing/node_modules/@winglang/sdk/src/shared-aws/queue.inflight.ts:41:5)
     │ at handle (/home/runner/work/wing/wing/examples/tests/sdk_tests/queue/pop.test.w:8:3)
     └ at handler (/home/runner/work/wing/wing/examples/tests/sdk_tests/queue/target/test/pop.test.tfaws/.wing/handler_c814f0c7.js:3:10)
One or more tests failed. Cleaning up resources...
```

### This happened:

The top shows the source text of the exact error (from `@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22`)

### I expected this:

**My** source context at the top (in this case, text from `pop.test.w:8:3`)

The full stack trace should still show the entire trace, but the context at the top is typically not useful if the code doesn't belong to me.

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
Fixed in #5550

There may be too little context now, but that can be its own issue
