### ISSUE TITLE
`cloud.Topic` intermittent AWS test failure

### ISSUE THREAD

**Issue by MarkMcCulloh** [winglang/wing#5053]
### I tried this:

https://github.com/winglang/wing/actions/runs/6990660035/job/19020417149

### This happened:

```
fail ┌ on_message.test.tfaws.107287 » root/Test.CY8vxJcGzF/env0/test:onMessage
     │ runtime error: assertion failed: c.peek() == 10
     │    --> examples/tests/sdk_tests/topic/on_message.test.w:24:3
     │    |   return c.peek() == 10;
     │    | ***, timeout: 10s);
     │    | 
     │ 24 | assert(c.peek() == 10);
     │    | ^
     │ at (/home/runner/work/wing/wing/examples/tests/sdk_tests/topic/on_message.test.w:24:3)
     │ at processTicksAndRejections (node:internal/process/task_queues:95:5)
     └ at handler (/home/runner/work/wing/wing/examples/tests/sdk_tests/topic/target/test/on_message.test.tfaws/.wing/handler_c87a2f2e.js:3:10)
```

```
fail ┌ no_blocking.test.tfaws.107287 » root/Test.xG1pdzI5wY/env0/test:topic subscribers are invoked without blocking
     │ runtime error: assertion failed: counter.peek() == 1
     │    --> examples/tests/sdk_tests/topic/no_blocking.test.w:24:3
     │    | // after a while, the counter should be 1
     │    | util.waitUntil(inflight () => *** return counter.peek() == 1; ***, interval: 1s, timeout: 30s);
     │    | 
     │ 24 | assert(counter.peek() == 1);
     │    | ^
     │ at (/home/runner/work/wing/wing/examples/tests/sdk_tests/topic/no_blocking.test.w:24:3)
     │ at processTicksAndRejections (node:internal/process/task_queues:95:5)
     └ at handler (/home/runner/work/wing/wing/examples/tests/sdk_tests/topic/target/test/no_blocking.test.tfaws/.wing/handler_c8f91e0a.js:3:10)
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
Not intermittent, will be addressed in https://github.com/winglang/wing/pull/5055
