### ISSUE TITLE
weird error thrown

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#5347]
### I tried this:

```sh
wing test -t tf-aws main.w
```

#### main.w
```
bring cloud;
bring util;

let bucket = new cloud.Bucket();

test "weird error" {
  let assertThrows = (expected: str, block: (): void) => {
    let var error = false;
    try {
      block();
    } catch actual {
      assert(actual.contains(expected));
      error = true;
    }
    assert(error);
  };
  let ACCESS_DENIED_ERROR = "<Error><Code>AccessDenied</Code><Message>Request has expired</Message>";

  let KEY = "tempfile.txt";
  let VALUE = "Hello, Wing!";

  bucket.put(KEY, VALUE);

  let getSignedUrl = bucket.signedUrl(KEY, { duration: 1s });

  util.sleep(2s);

  assertThrows(ACCESS_DENIED_ERROR, () => {
    util.shell("curl \"{getSignedUrl}\"");
  });
}
```

### This happened:

```sh
✔ Compiling bucket/signed_url.test.w to tf-aws...

✔ terraform init

✔ terraform apply

✔ Setting up test runner...

✔ Running tests...

fail ┌ signed_url.test.tfaws.665637 » root/Test.KATfDaXybq/env0/test:weird error
     │ runtime error: assertion failed: error
     │    --> libs/wingsdk/src/helpers.ts:14:11
     │    | 
     │    | export function assert(condition: any, message: string): asserts condition {
     │    |   if (!condition) {
     │ 14 |     throw new Error("assertion failed: " + message);
     │    |           ^
     │ at assert (/home/user/github/wing/libs/wingsdk/src/helpers.ts:14:11)
     │ at assertThrows (/home/user/github/wing/examples/tests/sdk_tests/bucket/signed_url.test.w:17:5)
     │ at processTicksAndRejections (node:internal/process/task_queues:95:5)
     │ at handle (/home/user/github/wing/examples/tests/sdk_tests/bucket/signed_url.test.w:30:3)
     └ at handler (/home/user/github/wing/examples/tests/sdk_tests/bucket/target/test/signed_url.test.tfaws/.wing/handler_c841b444.js:3:10)
One or more tests failed. Cleaning up resources...
✔ terraform destroy

 
 
Tests 1 failed (1)
Test Files 1 failed (1)
Duration 1m3.75s
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by garysassano** [comment]
The culprit is #5348

**Comment by staycoolcall911** [comment]
Thanks for reporting @garysassano! IIUC the error you see is because the assertion fails when no exception is thrown in `util.shell()` (and that doesn't happen because of #5348 as you stated correctly). I'm not sure this issue adds anything on top of #5348 - please reopen and update the title, description if you disagree.
