### ISSUE TITLE
bundling error when using computed struct value

### ISSUE THREAD

**Issue by eladcon** [winglang/wing#5458]
### I tried this:

```wing
struct s {
  a: str;
}

test "" {
  let x: s = s{
    a: () => {
      return "b";
    }()
  };
}
```

### This happened:

```
fail ┌ main.wsim » root/env0/test:
     │ runtime error: Failed to bundle function: Error: Build failed with 1 error:
     │ inflight.$Closure1-1.js:11:39: ERROR: Unexpected "=>"
     │    --> ../../../Users/eladcohen/.nvm/versions/node/v18.14.2/lib/node_modules/winglang/node_modules/@winglang/sdk/src/shared/bundling.ts:63:11
     │    | 
     │    | if (esbuild.errors.length > 0) {
     │    |   const errors = esbuild.errors.map((e) => e.text).join("\n");
     │ 63 |   throw new Error(`Failed to bundle function: ${errors}`);
     │    |         ^
     │ at  (inflight.$Closure1-1.js:11:39)
     │ at createBundle (/Users/eladcohen/.nvm/versions/node/v18.14.2/lib/node_modules/winglang/node_modules/@winglang/sdk/src/shared/bundling.ts:63:11)
     │ at loadBundleOnce (/Users/eladcohen/.nvm/versions/node/v18.14.2/lib/node_modules/winglang/node_modules/@winglang/sdk/src/shared/sandbox.ts:102:33)
     │ at call (/Users/eladcohen/.nvm/versions/node/v18.14.2/lib/node_modules/winglang/node_modules/@winglang/sdk/src/shared/sandbox.ts:121:5)
     │ at withTrace (/Users/eladcohen/.nvm/versions/node/v18.14.2/lib/node_modules/winglang/node_modules/@winglang/sdk/src/simulator/simulator.ts:673:24)
     └ at runTest (/Users/eladcohen/.nvm/versions/node/v18.14.2/lib/node_modules/winglang/node_modules/@winglang/sdk/src/target-sim/test-runner.inflight.ts:47:7)
```

### Is there a workaround?

Add a variable for the closure:
```ts
struct s {
  a: str;
}

test "" {
  let f = () => {
    return "b";
  };
  let x: s = s{
    a: f()
  };
}
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Added a workaround - add a variable for the closure:

```ts (wing)
struct s {
  a: str;
}

test "" {
  let f = () => {
    return "b";
  };
  let x: s = s{
    a: f()
  };
}
```

**Comment by Chriscbr** [comment]
Thanks for the minimal repro @eladcon
