### ISSUE TITLE
String tokens aren't lifted properly (SyntaxError: "undefined" is not valid JSON)

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#6960]
### I tried this:

I wrote this Wing program:

```js
bring aws;
bring cloud;

class CustomQueue {
  queue: aws.IAwsQueue;
  new() {
    let queue = new cloud.Queue();
    if let awsQueue = aws.Queue.from(queue) {
      this.queue = awsQueue;
    } else {
      throw "only AWS targets supported";
    }
  }
  pub inflight push(item: Json) {
    CustomQueue._push(this.queue.queueUrl, item);
  }
  extern "./queue.js" inflight static _push(queueUrl: str, item: Json);
  pub onLift(host: std.IInflightHost, ops: Array<str>) {
    if let awsFn = aws.Function.from(host) {
      let actions = MutArray<str>[];
      if ops.contains("push") {
        actions.push("sqs:SendMessage");
      }
      awsFn.addPolicyStatements({
        actions: actions.copy(),
        effect: aws.Effect.ALLOW,
        resources: [this.queue.queueArn]
      });
    } else {
      throw "only AWS targets supported";
    }
  }
}

let q = new CustomQueue();

test "push to the queue" {
  q.push({ "key": "value" });
}
```

Then I ran an end-to-end test on AWS with `wing test -t tf-aws main.w`.

### This happened:

A runtime error occurs:

```
fail ┌ main.tfaws.370309 » root/Test.aohclFq6RE/env0/test:push to the queue
     │ Error: SyntaxError: "undefined" is not valid JSON
     │ at parse :undefined:undefined
     │ at /var/handler_c80f0836.cjs:17:56
     │ at /var/handler_c80f0836.cjs:20:1
     │ at handler /var/handler_c80f0836.cjs:27:1
     └ at handleOnceNonStreaming file:///var/runtime/index.mjs:1173:29
```

If you look at the generated JS bundle, you'll see it references a token string like "WING_TOKEN_TFTOKEN_TOKEN_21" but the Terraform configuration only references other token strings like "WING_TOKEN_TFTOKEN_TOKEN_24".

### Wing Version

0.79.13

### Node.js Version

v20.12.2

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
It seems like the issue comes down to how CDKTF produces a fresh "token" each time you access a property on a CDKTF construct, like `myQueue.queueUrl`.

For a little more details, the compiler generates some methods like this on each preflight class right now:

```js
_liftedState() {
  return {
    ...(super._liftedState?.() ?? {}),
    $this_queue_queueUrl: $stdlib.core.liftObject(this.queue.queueUrl),
  };
}
get _liftMap() {
  return ({
    "push": [
      [CustomQueue, ["_push"]],
      [this.queue.queueUrl, []],
    ],
    "$inflight_init": [
      [CustomQueue, []],
      [this.queue.queueUrl, []],
    ],
  });
}
```

`_liftedState()` is used to populate information when constructing the inflight client of the class is generated (via `toInflight()`). `_liftMap` is used by the SDK to figure out what environment variables to add to the hosts (like the cloud.Function that accesses the queue). Basically, since we access `this.queue.queueUrl` in each of these methods, a different token is added as an environment variable vs being accessed in the inflight code, so you end up with something like `WING_TOKEN_1` getting added to `cloud.Function`'s configured environment variables ,but `process.env["WING_TOKEN_2"]` is added to the inflight code. That's awkward.

The good news is it's possible to work around this by changing Wing code so that the underlying getter on the CDKTF class is only accessed once. So define `this.queueUrl = this.queue.url` in your constructor, and use `this.queueUrl` everywhere.

But this is pretty awkward / ought to be fixed in some way.

----

Some solution ideas:

- Fix this upstream - see issue https://github.com/hashicorp/terraform-cdk/issues/2658
- Try to change the compiler code gen / SDK in some way to somehow cache values that are accessed inside the _liftedState / _liftedMap methods. e.g. replace `this.queue.queueUrl` inside `_liftMap` and `_liftedState` with `this._liftCache["$this_queue_queueUrl"]`.
- Try to automate the transformation that's enacted by the fix -- insert a new fake class field corresponding to the nested class field. This might fix the particular case, but I think it would break other code (where a class field is expected to change during the construction of the construct tree).
