### ISSUE TITLE
Unbundle-able libraries fail with cryptic error

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#7073]
### I tried this:

I wrote a Wing app that uses the `crypto-hash` npm library:

```js
// main.w
bring cloud;

class Util {
  pub extern "./util.js" static inflight hash(query: str): str;
}

test "getUrl" {
  log(Util.hash("hello"));
}
```

Extern code:

```js
import { sha256 } from "crypto-hash";

export const hash = async (query) => {
    return sha256(query, { outputFormat: "hex" });
}
```

### This happened:

When I run `wing test` I get this error:

```js
fail ┌ main.wsim » root/Default/test:getUrl
     │ Error: TypeError: Invalid URL
     │    --> target/test/main.wsim/.wing/handler_c8e701de.sandbox.cjs.bundle/index.cjs:10:56
     │    | var __hasOwnProp = Object.prototype.hasOwnProperty;
     │    | var __name = (target, value) => __defProp(target, "name", { value, configurable: true });
     │    | var __esm = (fn, res) => function __init() {
     │ 10 |   return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
     │    |                                                        ^
     │ at __init /Users/chrisr/dev/wing-test/target/test/main.wsim/.wing/handler_c8e701de.sandbox.cjs.bundle/index.cjs:10:56
     │ at js /Users/chrisr/dev/wing-test/util.js:1:1
     │ at __init /Users/chrisr/dev/wing-test/target/test/main.wsim/.wing/handler_c8e701de.sandbox.cjs.bundle/index.cjs:10:56
     │ at hash /Users/chrisr/dev/wing-test/main.w:4:3
     └ at /Users/chrisr/dev/wing-test/main.w:8:3
```

### I expected this:

I expected the example to work, or to have a more helpful error

### Is there a workaround?

Avoid using npm libraries that use features which prevent their code from being bundled like `import.meta.url`

### Wing Version

0.83.8

### Node.js Version

20.12.2

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
For this particular example, we might be able to work around it by adding code to Wing SDK for "shimming" in a substitute value for `import.meta.url` that works in many circumstances: https://github.com/evanw/esbuild/issues/3099

Though it might be worthwhile to understand how broad this issue is (what fraction of libraries can be reliably bundled without esbuild warnings or runtime errors?)
